### ISSUE TITLE
Add fallback placeholder image to terra-image component

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#1088]
# Issue Description
Need to add ability to displays an fallback image while the image is being loaded. If the src image successfully loads, the fallback image is replaced with the src image. Otherwise, the fallback image is left as is. Look at [terra-profile-image for implementation details](https://github.com/cerner/terra-core/blob/master/packages/terra-profile-image/src/ProfileImage.jsx)

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
If the src image successfully loads, the fallback image is replaced with the src image. Otherwise, the fallback image is left as is.

**Comment by cwalten** [comment]
# Tech design for adding a placeholder image to the Image component and refactoring ProfileImage to utilize this
## Summary:
Logic will be moved from ProfileImage to Image which will control loading the src image and providing a placeholder image both while loading and in case of failure. This logic will only be executed should a placeholder prop be provided. Otherwise, nothing will render during loading or in case of failure (current implementation). ProfileImage should then be able to utilize this functionality by providing the ProfileImage svg placeholder as a prop.

## React Props Added
### Image 
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| placeholder | string | undefined | An svg file which will be put in place of a loading or failed src image |

## Examples
```
import placeholderImage from './placeholder.svg';

<Image
  src={'/my/server/media/route'}
  placeholder={placeholderImage}
/>
```

```
// Placeholder image is built into this component
<ProfileImage
  src={'/my/server/media/route'}
/>
```

**Comment by bjankord** [comment]
> This logic will only be executed should a placeholder prop be provided. Otherwise, nothing will render during loading or in case of failure (current implementation).

I think we should make this logic default behavior for Image. To do this, we'd make the placeholder prop have a defaultProp value of string of a generic SVG fallback image.

**Comment by cwalten** [comment]
@tbiethman discussed this with me, and we had decided this was not desired default behavior, especially for backwards compatibility. Maybe he has a comment on this as well?

**Comment by tbiethman** [comment]
@bjankord I was thinking it'd be easier for consumers to opt into having a placeholder if they want one rather than having them opt out somehow if they don't. I didn't know how consumers would feel about placeholders being defaulted without a version bump; the APIs are passive but functionally things are changing quite a bit. I also didn't want to block development on these APIs with functional discussions about what the default image should be when the consumers of this logic (so far, anyway) will be using their own concept-specific placeholder images.

If you don't have any concerns with these things, I think defaulting something is fine. Otherwise, we could circle around on the default value with more discussion after these initial changes are made.

**Comment by mjhenkes** [comment]
I agree with @tbiethman s passivity concerns and having the placeholder be opt in.

**Comment by bjankord** [comment]
@cwalten @tbiethman @mjhenkes Ok I'm good with that. +1 on tech design.

**Comment by tbiethman** [comment]
+1

**Comment by mjhenkes** [comment]
+1
