### ISSUE TITLE
Create Consistent PropsTable Layout

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#1201]
# Issue Description
The props-table displays inconsistently for each component; the column sizes vary depending on the prop names, prop types and descriptions. Additionally some components don't wrap their text and blow out beyond the screen size which makes it harder to read and navigation. 

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
We want to create a consistent layout/style for all props.

**Comment by Blackop778** [comment]
# Tech Design for PropsTable
## Summary:
Use CSS to limit the maximum width of each column in the PropsTable

## CSS Classes:
| Selector         | Description |
|------------------|-------------|
| pre | `white-space: pre-wrap` These won't text wrap otherwise|
|.prop-Table-Name .prop-Table-Required .prop-Table-Default | `max-width: 10%;` These columns are usually shorter so they need less space |
| .prop-Table-Type .prop-Table-Description | `maximum-width: 35%;` These columns are usually the longest so they should have the most allocated space |

**Comment by emilyrohrbough** [comment]
Looks good to me. +1

**Comment by bjankord** [comment]
We don't want to target all `pre` elements. Using `.prop-Table pre` It would be better to scope that `pre` styling so its only applied to pre element in the prop-table component. Other than that, +1 on the tech design.

**Comment by yuderekyu** [comment]
+1
