### ISSUE TITLE
Add theming for Button to meet cerner-consumer-theme requirements

### ISSUE THREAD

**Issue by samvaity** [cerner/terra-core#1246]
# Issue Description
Uplift button theming to meet cerner-consumer-theme requirements.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by samvaity** [comment]
# Button Themeing Tech Design 
## Summary:
Adds theming variables and web driver IO tests to Button component. 

## Themeable Styles


- Font Family - `neutral`,  `utility`,  `emphasis`, `de-emphasis` and  `action`
- Active and focux Border width - `neutral`
- Active Border width - `neutral`
- Active and Focus Box shadow - `neutral`,  `emphasis` and  `action`
- Active Box Shadow - `neutral`,  `emphasis` and  `action`
- Hover Box Shadow - `neutral`,  `emphasis` and  `action`

## Responsiveness & Accessibility
None to consider for uplift.

**Comment by emilyrohrbough** [comment]
- Font-family will be inherited from the base component and should not be themed on this level.

- Instead of adding a `border-width` for each button variant, we should remove the `border-color` variable and combine the variables to be `border`.

- Active and Focus Box shadow is not needed. Already included: see [neutral](https://github.com/cerner/terra-core/blob/master/packages/terra-button/src/_variables.scss#L5), [emphasis](https://github.com/cerner/terra-core/blob/master/packages/terra-button/src/_variables.scss#L24), and [action](https://github.com/cerner/terra-core/blob/master/packages/terra-button/src/_variables.scss#L62)

- If we need to add box shadow styling for both the `active` and `hover` states, we will need to add it for all button variants.

**Comment by samvaity** [comment]
@emilyrohrbough 

- Cerner consumer theme uses `Roboto` font family across all the button variants. By keeping this theme-able the font-family can remain consistent across a theme for a button variant. Also, we can have it to have a default  `inherit` in terra-core ?

- Currently, we need `border-width` only for `neutral`. Should we still consider changing it to `border` for all variants?

- Removed  Active and Focus Box shadow from tech design.

- I had talked with @bjankord  on this. He mentioned adding only the variables needed as of now for the cerner-consumer-theme requirements.

**Comment by emilyrohrbough** [comment]
The current styles for button implement are implemented via [this mixing](https://github.com/cerner/terra-core/blob/master/packages/terra-button/src/_mixins.scss#L4). To only add theme for the variants the need the styles, this need need refactored.

**Comment by dylan-sftwr** [comment]
@samvaity , I think that we will be wanting to merge all `border` styles into a single CSS custom property. Though #1199 is closed, it was still called out as an issue in my `form-input` PR (#1235) by @bjankord. :)

**Comment by jmsv6d** [comment]
There are issues with having a different border widths for focus/active states. With the current styling it will cause odd resizing/shifting to occur. We saw this in the button group. In order to accomplish the consumer styling, either the `box-sizing` property will need to be set to `border-box` or an inset box-shadow can give the same effect.

**Comment by emilyrohrbough** [comment]
Like @jmsv6d mentioned, the an inset box shadow is how we are currently obtaining a 'double' border switch when altering the different states.

**Comment by dylan-sftwr** [comment]
@jmsv6d or @emilyrohrbough , do you have an example of this "double border" effect that's already been implemented? I glanced quickly at button-group, but I could just be misunderstanding / missing it.

**Comment by bjankord** [comment]
In the consumer theme, [this line](https://github.cerner.com/terra/cerner-consumer-theme/blob/master/src/scss/_button-group.scss#L20) and [this line](https://github.cerner.com/terra/cerner-consumer-theme/blob/master/src/scss/_button-group.scss#L16) apply a double border via box-shadow.

**Comment by benbcai** [comment]
@dylan-sftwr You can also take a look at this [comment](https://github.com/cerner/terra-core/pull/1155#discussion_r163912348) and the update to use an inset box-shadow to get the effect of a focus ring for the mock theme in button-group.

**Comment by dm123455** [comment]
+1

**Comment by bjankord** [comment]
+1 on updated tech design.

**Comment by mjhenkes** [comment]
+1

**Comment by dylan-sftwr** [comment]
+1

**Comment by PaulSolDev** [comment]
JIRA created
