### ISSUE TITLE
Terra Button has no default for hover-background-color

### ISSUE THREAD

**Issue by cwalten** [cerner/terra-core#1365]
# Issue Description
Terra button has a theme variable with no backup color, causing errors when the variable is undefined

https://github.com/cerner/terra-core/blob/master/packages/terra-button/src/_variables.scss#L93

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

## Expected Behavior
Button theme variable would be expected to have a default

## Current Behavior
No backup color

## Environment
* Component Version: 2.3.0

**Comment by bjankord** [comment]
@cwalten Can you tell us a bit more about the errors you are seeing. That we'll help us address this better.

**Comment by cwalten** [comment]
@bjankord I had updated terra-button by accident on a project. Webpack gave me a warning that there was no fallback value for that variable referenced above. When I pulled up the webpack server for said project, it claimed the variable was undefined and had no fallback, hence not rendering the page (invalid css). Since every other usage of a variable in any package in this repo I've seen has a fallback, it seems incorrect to have this one not follow that pattern.

**Comment by madelineisabelle** [comment]
We're seeing this in ion-demographics as well. We're seeing it for List as well with the warning "-terra-list-item-background-color' is undefined and used without a fallback "

**Comment by bjankord** [comment]
Leaving the fallback value in the CSS custom property undefined is a design choice we've made. e.g. ` vertical-align: var(--terra-form-checkbox-vertical-align);` The idea behind this is that for some styles, we want them to be themable, but we don't want to provide a value for the default theme, often because we want to use whatever the browser default is. This syntax ` vertical-align: var(--terra-form-checkbox-vertical-align);` essentially says, use whatever value `--terra-form-checkbox-vertical-align` is. In our default theme, we may not provide that, which translates to the browser retaining whatever style it has applied to the specific the style.

This is helpful in our form styles for radio and checkbox controls where we want to let the browser default styles be applied, but allow some of the styles the browser is providing by default to be themed.

If you are using the postcss-custom-properties plugin, it will likely through a warning about these styles. The warning can be disregarded.  `vertical-align: var(--terra-form-checkbox-vertical-align);` is valid CSS, and in browsers that don't support it, nothing will break. The browser will read this style the same as if it was ` vertical-align: random-text-not-a-real-value;` and skip over trying to render it. The postcss plugin is warning that it will not be able to extract a fallback value as none has been provided. 

You mentioned that its `not rendering the page (invalid css)`. Is this true that the page is not rendering? That could be an issue we need to dig into further.

**Comment by cwalten** [comment]
That is sound reasoning, but filling project webpack logs with warnings is noise that can hide bigger issues. For example, demographics has 5 warnings, I can only imagine what a larger project will have. Is there a way to suppress these warnings? If it is a known choice Terra is making, I don't think we need to see those logs.

The page was not loading (gray error screen used by webpack dev server). However, @madelineisabelle mentioned that my failure might have been because I was mixing React 15 and 16 (accidentally). I will look more into this issue on my side.

**Comment by bjankord** [comment]
@cwalten You can turn warnings off for the postcss-custom-properties plugin by setting the [warnings option to false and passing it to the plugin](https://github.com/postcss/postcss-custom-properties#warnings). If/when [this PR is implemented](https://github.com/postcss/postcss-custom-properties/pull/106), you will be able to control warnings for the postcss-custom-properties plugin more modularly, only turning off warnings for this specific issue.
