### ISSUE TITLE
terra-menu location not proper on click of terra-button

### ISSUE THREAD

**Issue by sm031313** [cerner/terra-core#1442]
# Issue Description
When I click on a terra-button, the terra-menu does not appear right below the button. Here is a screenshot-
![image](https://user-images.githubusercontent.com/38588332/39085592-91d53e60-45a2-11e8-8a91-5c8ca0295e76.png)

**Just a random thought** - could this be due to some kind of incompatibility between any of the terra components' and react components' versions?

## Issue Type
- [ ] Bug

## Expected Behavior
On click of the terra-button, the terra-menu should appear as though it is attached to the terra-button

## Current Behavior
On click of the terra-button, the terra-menu appears to the right-side of the screen whereas the terra-button is at the top

## Steps to Reproduce
[Prototype.zip](https://github.com/cerner/terra-core/files/1934721/Prototype.zip)
1. Unzip the attached Prototype.zip file
2. There is no `node_modules` folder attached in the zip. So you might have to `npm install` it. The application runs on port 8080. Just FYI.
3. Please comment out the code in `node_modules\terra-button-group\lib\ButtonGroup.scss file` in order for the page to load. (Yeah! That is another issue, I'm not sure if it has been reported, but if you are using ButtonGroup component of `terra-button-group`, our pages don't load, with the current react and terra versions we are using, which is either latest or almost the latest version)
4. Type `webpack-dev-server` command to get the application running
5. In the UI, click on any of the Buttons to reproduce the issue. `MenuButtonsItems.js` contains the source code for thes `Button` and `Menu` components.

## Environment
I have attached the project **Prototype.zip** which contains `Package.json` and my source code (doesn't contain my node_modules folder though)
* Component Version: information available in **Package.json** in the attached zip file
* Browser Name and Version: Firefox, Chrome and Edge (latest as per the date 04/21/2018)
* Operating System and version (desktop): Windows 10

**Comment by emilyrohrbough** [comment]
@sm031313 
To resolve the issue you are seeing with ButtonGroup, you will need to update your webpack configuration. Adding `ident: 'postcss',` to this the `postcss-loader` options. What is happening is that `postcss-loader` is attempting to load `./postcss.config` file which was not supplied and results in the error. Adding the `ident` key resolves this. More information on this issue can be found [here](https://github.com/cerner/terra-dev-site/issues/35).

**Comment by sm031313** [comment]
This is how my config looks like in my `webpack.config.js` file. Inspite of making the following changes, the output is still the same. I am not getting the expected output.

```
       {
        test: /\.(sass|scss|css)$/,
        use: [
          'style-loader',
          'css-loader',
          'sass-loader',
          // 'postcss-loader',
          {
            loader: 'postcss-loader',
            options: {
              ident: 'postcss',
            },
          },
        ]
      },
```

**Comment by sm031313** [comment]
The Node version I'm using is **9.11.1** and the React version is **16.3.1**

**Comment by BenBoersma** [comment]
Mainly the issue your seeing is that you are defining the target reference of the menu as the whole div surrounding all the buttons. 
```
render() {
 return {
  <div ref={this.setButtonNode} className="menu-component-outer">
     <Menu  targetRef={this.getButtonNode} isOpen={this.state.open} onRequestClose={this.handleRequestClose} contentWidth="240">
....
 }
}
```
Menu's targetRef prop is used to determine what node to use as an anchor. In this case you have set the div surrounding the buttons as the anchor because when the Menu is called to open, "this.buttonNode" is still set to its value from the "ref={this.setButtonNode}" code. 

To get the functionality it sounds like you're looking for, you need to make the anchor point change dynamically, either by setting "this.buttonNode" variable to a different based on clicks or having "getButtonNode()" figure out what node it needs to return based on the last click.

Minor side issue, Terra assumes directionality has been defined and thus you aren't getting some of the css that was supposed to come in with Terra. Changing your html tag in index.html to define "dir" fixes this issue.
```
<html dir="ltr">
...
</html>
```
