### ISSUE TITLE
Terra Select - make size of list dropdown configurable

### ISSUE THREAD

**Issue by ShantiiP** [cerner/terra-core#1579]
# Issue Description
the dropdown list height of Terra Select spills over the size of the modal

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
1. When user clicks on terra select field, the list remains within the modal.  
Have the list display below the dropdown field, with the dropdown list height filling any available space in the modal below the dropdown and 10px above the footer.

## Current Behavior
1. Click on terra select field to display list.  Note that list spills over the size of the modal.

## Steps to Reproduce
1. Click on terra select field to display list.  Note that list spills over the size of the modal.
![image](https://user-images.githubusercontent.com/39775691/41017840-d5409b18-6924-11e8-876a-d55c5c0634e7.png)

[Consumer select component](https://pages.github.cerner.com/terra/cerner-consumer-theme/build/master/#/site/components/core/site/form-select/index)

**Comment by StephenEsser** [comment]
Hi @ShantiiP,

The Select dropdown height is configurable. A custom maxHeight can be specified within the dropdownAttrs.

```
<Select dropdownAttrs={{ style: { maxHeight: '300px' } }} />
```

There is an example on the documentation page. The OptGroup example sets a custom maxHeight: http://engineering.cerner.com/terra-core/#/components/terra-form-select/form-select/select

**Comment by WhiteLight1107** [comment]
@StephenEsser We have a requirement for a select component to display a dynamic long list of items and should adjust to the parent's dimensions....also isn't the above setting a custom style for the dropdown attributes, pretty sure that would go against OCS.

Thank You

**Comment by StephenEsser** [comment]
@WhiteLight1107

I would disagree. A user setting a max height on a dropdown is a common pattern for most of, if not all, of the open source Select components. A long list of content is difficult to discern options. 

I think the main concern here is the syntax. If the maxHeight was abstracted into a prop and a user was not aware it was being applied as an inline style I don’t think this concern would have been raised.

<Select maxHeight=“300px” />

I think your concern is a matter of perception because you are aware it is applied as an in-line style. 

The ability to customize a maxHeight using the custom attributes was an intentional design decision. There is explicit code within the Select component to honor the user value provided within those custom attributes. 

Based on these concerns I think there would be value in adding a first class maxHeight prop to the Select component to abstract the implementation.

**Comment by StephenEsser** [comment]
I've gone back and fourth on this. 

The incredibly frequent necessity of setting a maxHeight warrants at least a war room discussion to gather opinions. The change would be passive and provide a cleaner first class API. 

```
 <Select dropdownAttrs={{ style: { maxHeight: '300px' } }} />
```
VS
```
 <Select maxHeight={300} />
```

Whether this change is made I think it is worth reiterating the Select was designed with the intention of allowing a user to set the maxHeight of the dropdown one way or another.

For additional context we're not the first to stumble upon this problem. At a quick glance these appear to be the three approaches used in some form between most of the other UI libraries.

1. Provide a first class prop to allow a user to apply styles to the drop down. ( What we have now )
2. Provide a first class maxHeight prop and let the user set it.
3. Default a maxHeight for all Selects to be the same.

## Examples

### Ant Design
Solved this approach the same way we have. They expose a dropdownStyle API to allow a user to set a maxHeight: https://ant.design/components/select/

### Material UI
First class maxHeight prop: https://v0.material-ui.com/#/components/select-field

### Semantic UI
Defaults the maxHeight automatically. I do not see a way for the user to adjust it, it is decided for them: https://react.semantic-ui.com/addons/select

@neilpfeiffer Do you have a clear desired approach UX would want in regards to the height of the Select?

**Comment by dylan-sftwr** [comment]
@StephenEsser I agree, I'd be interested to hear opinions in War Room
