### ISSUE TITLE
[terra-form-select] Same style variable used for different styles

### ISSUE THREAD

**Issue by nagrawal3** [cerner/terra-core#1598]
# Issue Description

In the terra-form-select _OptGroup.module.scss file following variables are used for multiple styles which don't allow to theme them.
1. terra-select-optgroup-label-background-color (used for background color and color styles)
2. terra-select-optgroup-label-line-height (used for line-height and padding styles)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

Different variables should be used for different styles

## Environment

* Component Version: 4.3.0
* Browser Name and Version:
* Operating System and version (desktop or mobile):

**Comment by nagrawal3** [comment]
Also found one more variable --terra-select-padding-bottom in _Frame.module.scss file which is used twice with two different values for different variant of select. Is that intended behavior?

**Comment by StephenEsser** [comment]
@nagrawal3 

That one was intended, although it is a little awkward. If you choose to override the default styles it will be necessary to theme other variables to readjust the height.

This was done so that there wasn't a variable for each different variant. If you theme the bottom padding you'll need to theme the margin top of the search input.

Let me know if you run into any issues with this. 

You'll notice that the margin top of the search is identical to the padding bottom:
https://github.com/cerner/terra-core/blob/master/packages/terra-form-select/src/_Frame.module.scss#L147
