### ISSUE TITLE
Tabs dropdown not dismissing when reselecting tab header on Phone devices

### ISSUE THREAD

**Issue by PaulSolDev** [cerner/terra-core#1602]
# Issue Description

**Context**- On the Terra UI site while using an iPhone selecting the tab header opens the dropdown but reselecting the header does not dismiss the dropdown.  Works as expected on desktop devices and closes the dropdown on the second interaction

![tabs example](https://user-images.githubusercontent.com/29487301/41437069-3be6aedc-6fe9-11e8-933d-df40c71851b6.png)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

Function the same on any device and close dropdown when selecting outside of the menu (including the tab header where the dropdown originated).
## Steps to Reproduce

1. Login to Terra UI and open Tabs from an iPhone
2. Select the tab header (dropdown appears)
3. Re-select the tab header (dropdown does not dismiss)

## Environment

* Component Version: iPhone 5s and iPhone 8
* Browser Name and Version: Safari

**Comment by mjhenkes** [comment]
@PaulSolDev can you recreate this issue on http://engineering.cerner.com/terra-ui/#/home/terra-ui/index For either tabs or the select?

**Comment by BrandonKraus30** [comment]
I get the following error when tapping outside of the popup menu in the terra-tabs component on mobile:
"ERROR: Unable to preventDefault inside passive event listener due to target being treated as passive."

This error gets thrown in the [handleOutsideClick](https://github.com/cerner/terra-framework/blob/master/packages/terra-popup/src/_PopupContent.jsx#L175) function in _PopupContent.jsx and could be the cause of the issue being seen here.

**Comment by tomleewu** [comment]
Piggybacking on @BrandonKraus30, here's some more information. On Chrome, the following is shown when clicking on the tab header when the popup is open.
<img width="554" alt="screen shot 2018-08-01 at 8 47 45 am" src="https://user-images.githubusercontent.com/17147005/43525530-aeca22dc-9567-11e8-9221-6a0cafd0a22c.png">.

It leads to the `event.preventDefault()` call in [PopupContent's `handleOutsideClick` function](https://github.com/cerner/terra-framework/blob/master/packages/terra-popup/src/_PopupContent.jsx#L175).

The tap on the header will call the [onRequestClose function in _TabMenu.jsx](https://github.com/cerner/terra-core/blob/59bd29055cda77b0b12af8ee09db76d89497ef70/packages/terra-tabs/src/_TabMenu.jsx#L63) to close the popup, but since the click is not prevented, it also triggers the [onClick within _TabMenu.jsx](https://github.com/cerner/terra-core/blob/59bd29055cda77b0b12af8ee09db76d89497ef70/packages/terra-tabs/src/_TabMenu.jsx#L67) which re-opens the popup. Hence the following effect,

![giphy](https://user-images.githubusercontent.com/17147005/43526039-e5ce4604-9568-11e8-8c72-a77095fa444c.gif)

**Comment by BrandonKraus30** [comment]
After digging through this a little more, I believe a possible solution to this problem would be to update [react-onclickoutside](https://github.com/Pomax/react-onclickoutside) to its latest version 6.7.1 in [terra-hookshot](https://github.com/cerner/terra-framework/blob/master/packages/terra-hookshot/package.json#L34). There have been updates to react-onclickoutside that will prevent the passive error from occurring. A [preventDefault](https://github.com/Pomax/react-onclickoutside#regulating-evtpreventdefault-and-evtstoppropagation) prop set to true will need to be passed into the [HookshotContent](https://github.com/cerner/terra-framework/blob/master/packages/terra-popup/src/_PopupContent.jsx#L233) component in _PopupContent and then the [event.preventDefault()](https://github.com/cerner/terra-framework/blob/master/packages/terra-popup/src/_PopupContent.jsx#L178) in the handleOutsideClick of _PopupContent would no longer be needed.

Additional customProps passed in by react-onclickoutside will need to be removed in [HookshotContent](https://github.com/cerner/terra-framework/blob/master/packages/terra-hookshot/src/HookshotContent.jsx#L183) to prevent unrecognized props on DOM elements. I'm still looking into any unwanted side effects that updating react-onclickoutside might cause.
