### ISSUE TITLE
[terra-form-select] need a style variable to style text color for variant Search, Combobox, Multiple and Tag

### ISSUE THREAD

**Issue by nagrawal3** [cerner/terra-core#1617]
# Issue Description

With terra-form-select version 4.4.0, there is no way to change the text color for text entered in the input field for different variants available for select.

This is preventing to add a theme for the select field.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

A variable should be available which will allow styling select field for different themes.

## Environment

* Component Version: terra-form-select 4.4.0
* Browser Name and Version:
* Operating System and version (desktop or mobile):

**Comment by nagrawal3** [comment]
@bjankord I can work on this and provide the fix. Can I get the default color for the input text?

**Comment by bjankord** [comment]
If you use css like, `color: var(--terra-var-color-name);` it will allow the color to be inherited from body as it is now, but be themable if needed.  The idea behind this is that for some styles, we want them to be themable, but we don't want to provide a value for the default theme, often because we want to use whatever the browser default is or whatever value they inherit from body.

**Comment by nagrawal3** [comment]
discuss with @neilpfeiffer instead of adding another style variable for the input, we would inherit the base text color on the page.

**Comment by bjankord** [comment]
Resolved in #1624
