### ISSUE TITLE
Action Header title height changed

### ISSUE THREAD

**Issue by qinfen86** [cerner/terra-core#1783]
In our js file, Action Header title looks like this:
![screenshot from 2018-08-21 17-28-44](https://user-images.githubusercontent.com/14319987/44433355-8c603880-a56b-11e8-8111-8915784ba4e3.png)
After running the same code in engine, it looks like this, a super big header:
![screenshot-3](https://user-images.githubusercontent.com/14319987/44433361-92561980-a56b-11e8-9c6f-53f573704e1c.png)

So is this related my code or the orien layer will change that?

**Comment by yuderekyu** [comment]
We'll need more information on these projects (in an internal manner). My first thought is that an engine style has higher specificity than the action header styles. Check what styles are applied to the action-header, within the engine context. Looks like the line height or margins are off on the title.

**Comment by bjankord** [comment]
This issue is not related to terra-ui styles. Some non-terra-ui styles you are importing are likely causing the extra space. It appears that either extra padding or increased line-height is being applied. Inspect your styles in the browser and you should be able to find what non-terra-ui styles are being applied and changing the appearance.
