### ISSUE TITLE
Ability To Show Abstract Modal Up Top

### ISSUE THREAD

**Issue by papasmile** [cerner/terra-core#1881]
# Feature Request

## Description
We are working on a mobile application with a fixed, full-screen view.  We've extended AbstractModal for ease of use with Redux.  However, when a software keyboard is displayed, there is no way to adjust the position of our modal.

Requesting addition of a 'showOnTop' prop which would position modal at the top of the screen (instead of the middle).  False by default, we've found a minimal amount of CSS changes would be need (e.g. `top: 10px; transform: translateX(-50%)`).

We'd be happy to try and contribute that change :)

## Additional Context / Screenshots
For additional info on our use case, feel free to contact me directly at Ismail.Jones at Cerner.com.

**Comment by dkasper-was-taken** [comment]
To start you should not be consuming AbstractModal directly, it is a lower level structural component. If you are doing so you are doing it wrong, so I question your implementation of Redux in your extension to begin with. Please switch to using one of the UX approved modals, ModalManager, DialogModal, or NotificationDialog.

Also this functionality has a myriad of problems. It does not take into account the size of the modal, so that CSS would be broken to begin with. We should not be treating modals different to account for 1 browsers keyboard, as Android doesn't behave the say way as iOS. We should have device specific code.

Closing.

**Comment by bjankord** [comment]
If this is needed by your team, we'd recommend adding this CSS, `top: 10px; transform: translateX(-50%)` via the `classNameModal` prop. This use-case hasn't been requested enough to consider incoporating it into a reusable component.
