### ISSUE TITLE
[terra-demographics-banner] Add new features

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-core#1897]
# Enhancement
* Switch `br` tags to `spans`. Use `font-weight` instead.
* Update `age` prop to take a node

https://zpl.io/bJvJgGr

**Comment by yuderekyu** [comment]
Append `yrs` to whatever value is passed into the `age` prop. `yrs` will not be bold. This will need translations.

**Comment by JakeLaCombe** [comment]
The age prop is designed to be agnostic for unit of time. Also, infants are usually measured in months. I don't think that's something we should add to the banner.

**Comment by yuderekyu** [comment]
That's fair - the callouts have the age value bold, and the unit non bold. Maybe we can add a unit of time prop?

**Comment by yuderekyu** [comment]
Yeah, we'll have to sync with UX on this then. The current implementation works best for that

**Comment by neilpfeiffer** [comment]
The UX design may not be possible with visual separation between the unit (10) and unit of measure (yrs). 

Depending on solution, age is calculated (or rather "should be calculated") by one of a central set of controlled formatters, which takes the birthdate/time and compares to now and renders back not just years, but potentially in months, weeks, days, hours, or a combination of units (10m 2d, 2d 3h, etc). 

Usually those age formatters return a simple string, and unless a formatter is bundled with UI (not recommended), or the return is a complex object instead of simple string, there is no reliable method to create the visual different.

**Comment by neilpfeiffer** [comment]
On a separate note - it was recently discovered that there are difference in how different Cerner standard age formatters return age, so it is being raised as an issue to standardize. Between Millennium, HealtheIntent, RevCycle, PowerChartTouch/Orion, all seem to do pediatric ages differently, which is not good. 

Usually Pediatrics/clinical concepts use the rule of 2: # of months until 2 years, # of days until 2weeks, # of hours until 2 days. But for more general clerical concepts, they may only need simpler 1year, 1month, 1week, etc.  I will be following up with this as a separate topic.

**Comment by yuderekyu** [comment]
Remove `br` tags and utilize `font-weight`.

**Comment by bjankord** [comment]
Discussed update the age prop to take a node instead.
