### ISSUE TITLE
Autofocus requested element when disclosing content in slide panel

### ISSUE THREAD

**Issue by kschuste** [cerner/terra-core#1973]
When disclosing content into the detail pane of a slide panel.  The focus doesn't automatically shift to the content that was disclosed.  A usability thought would be that since the user say clicked on something say a table row to show additional information in that detail pane, that their focus would go there; therefore, so should the focus of the page.  We are requesting that an additional prop be added to the SlidePanelManager or DisclosureManager that when content is disclosed, we can pass it a reference or selector to the input/element that we see best fit to have the focus.  

Current behavior is when using the slide-panel, when selecting a row in an item-collection or table, content is disclosed in the panel, then when hit tab, it will continue to tab downwards on the left first if there are more rows before moving to any content on the right.

**Comment by bjankord** [comment]
Related: #286

**Comment by kschuste** [comment]
Do we have an opinion on this issue?  We just want a prop to be exposed to be able to set the focus in the slide panel when we know we are disclosing content in it.  I believe it is different than the issue that was related.

**Comment by tbiethman** [comment]
Hey @kschuste, do you have any more thoughts here, or can this issue be closed?

**Comment by kschuste** [comment]
@tbiethman We can have the component set the focus for itself when disclosed in the slide panel, but that leads to more questions.  What if we have two components that when display by themselves in whatever they are disclosed in, can set the focus for each other; however, when are both displayed in a slide panel or modal, then who wins?  By using the prop, the components are agnostic as to what they are disclosed in and won't need to handle setting the focus, the prop will only allow the 1 element get the focus.

**Comment by bjankord** [comment]
>  What if we have two components that when display by themselves in whatever they are disclosed in, can set the focus for each other; however, when are both displayed in a slide panel or modal, then who wins? 

Can you expand on this, I'm unclear about this scenario/use-case.

**Comment by kschuste** [comment]
Lets say we are using the detail view with input fields and we want to auto-focus to the first input element, by itself disclose the detail view in the slide panel and auto-focusing on componentDidMount will work just fine.  Now lets say that detail view is now included in a wrapper component that also included another component with additional input fields and that additional component auto-focuses its first input on componentDidMount, if that wrapper component was disclosed in the slide panel, who would win without defining a selector?

<WrapperToDisclose>
  <DetailViewWithInputsWithFocusOnComponentDidMount>
  <AdditionalInputsWithFocusOnComponentDidMount>
</WrapperToDisclose

**Comment by tbiethman** [comment]
We discussed this issue in our weekly war room meeting and came to the following conclusions:

1. We think it does make sense for the SlidePanelManager to set focus to the panel content when the panel is opened. The focus would be on an internal panel container element itself, not the contents therein. This would result in screen-readers detecting and reading the panel disclosure content, with subsequent tabs navigating the panel's content.

2. The caveat with setting focus to the panel is that, unlike the ModalManager, we will not be able to return focus to the triggering element. The SlidePanelManager does not (and as far as we know should not) trap focus within the panel when it is opened, which allows focus to leave the panel and would make reseting focus on close potentially confusing to keyboard users. Such logic could be manually implemented with a callback from the panel content on dismissal if such functionality is desired, but there's not much that can be done consistently at a framework level.

3. I know I made the recommendation initially, but it seems like there are functional and technical issues with automatically setting focus on content elements in our progressive disclosure components. From a functional standpoint, its just inherently inaccessible and would result in screen-readers missing large sections of your panel contents without really knowing that they are missing anything. Technically, our disclosure methods that use a focus trap (e.g. the ModalManager) are going to be the last component mounting in a the component hierarchy and will steal focus away from your components if you try to set it manually on mount. We can't avoid this, nor would we want to due to the accessibility concerns I mentioned earlier. If your component requires quick access to specific input fields, your overall component may need design input to ensure your component will be accessible.

4. Regarding your example above with 2 auto-focusing components being disclosed, I just don't think a scenario like that would be supported. Just like you wouldn't be able to disclose a straight <Button /> component or something, there is an implicit API for components being rendered by a DisclosureManager (they get an `app` prop, they have to render a header with the proper disclosure controls, etc.). If you truly had two dueling components that had competing behaviors, they would need to expose props that enable/disable that impacted functionality so a parent component could control who needs to do what.

So there are changes we are making due to this issue: https://github.com/cerner/terra-framework/issues/321. I appreciate you acting as a catalyst for this discussion. I do realize that we're probably not solving the problem you're wanting solved. We are not going to expose a prop on the SlidePanel family of components that controls what gets focus. I think there is still a way forward for your desired functionality, but it may take more design work to be fully accessible.
