### ISSUE TITLE
Remove color prop from various components

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#1999]
# Feature Request

## Description
Remove color prop from terra-text, terra-heading, terra-status, and terra-progress bar.
Update doc to recommend people write custom CSS for foreground and background colors in progress bars so they can better manage the theming concerns related to these colors.

## @ Mentions
@mjhenkes @dkasper-was-taken @mayurikini

**Comment by bjankord** [comment]
I'd recommend we group this version bump when we do the OCS variable name update.

**Comment by kschuste** [comment]
Could there be a few standard colors that be defined depending on a variant type like what has been done for the terra-alert?  Red, Yellow, Green, ect, and have a custom variant to override?  I would rather not have the need to always define a color as I would be afraid could lead to inconsistencies if had multiple views each using a different shade of red.

**Comment by mjhenkes** [comment]
@kschuste We cannot support default colors because they would inherently be un-themeable. For example Red, orange, or brown may have different meanings depending on the component. Those default colors would have to be locked across themes to prevent breaking components. For your component you should be defining a specific theme variable for the intent of the theme, This will allow UX to appropriately them depending on your use and situation.
