### ISSUE TITLE
[terra-tag] additional features

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#2025]
## Enhancement
Adding additional features detailed here https://zpl.io/2Ewmqke 
- removable version of tag with a close/"X" icon
- potentially removing the custom icon/decorated version if not being used by any group
- adding a second visual style for use over alternate backgrounds (photos, darker solid colors, etc.)  
- add additional interaction styles for "pressed" state (new)

**Comment by avinashg1994** [comment]
I had a couple of questions regarding the implementation of this:

1. How should the implementation of the Close/"X" icon be :
   - Similar to the close icon of Action Header ?, i.e. a button : https://github.com/cerner/terra-core/blob/master/packages/terra-action-header/src/ActionHeader.jsx#L86-L102
   - Similar to the tag of multi select of terra-form-select ?, i.e. a span : https://github.com/cerner/terra-core/blob/master/packages/terra-form-select/src/shared/_Tag.jsx
2. I have some confusion w.r.t. to the hyperlink/navigation part as per the https://zpl.io/2Ewmqke:
The **basic construction** indicates that the Tag Label is hyperlink, whereas the **Interaction styles** indicates that the Tag Container can be pressed.
So should the navigation occur on the Tag click (similar to a button) "or" the Tag Label click (similar to a hyperlink) ?
3. Also i agree with the removal of the custom icon, since after a quick search in our internal github : [here](https://github.cerner.com/search?l=JSX&q=terra-tag&type=Code). It is clear that the custom icon is not being used.
So should we go ahead and remove that feature?
4. I quite did not understand the following requirement:
_"adding a second visual style for use over alternate backgrounds (photos, darker solid colors, etc.)"_
For what scenario is the dark style required?
If we do go ahead with the dark style, how do we want to implement it? (i.e. Taking input in the form of a prop)?
5. Also does the wireframe need to be revisited, since it was last updated in 2018?
