### ISSUE TITLE
[terra-list] List items display as hovered on mobile when not hovering

### ISSUE THREAD

**Issue by christinelang** [cerner/terra-core#2076]
# Bug Report

## Description
List items are appearing as hovered when user lightly touches the item but does not tap hard enough to select. The hover does not disappear once the user lifts finger from device.

![img_5097](https://user-images.githubusercontent.com/31296564/49188057-081e0e00-f32f-11e8-9058-32265ee2b8f6.PNG)
 
## Expected Behavior
Item should not continue to appear hovered once the user's finger in no longer on device.

## Environment
* Component Name and Version: terra-list 2.25.0

## @ Mentions
@StephenEsser

**Comment by nramamurth** [comment]
@christinelang The attached screenshot shows that it is on an iPad, is this issue reproducible on the desktop and phones as well? Could I also possibly get the link to the the dev site if Message Center has one or a piece of sample code for me to reproduce this issue?

The [List Item example](https://github.com/cerner/terra-core/blob/master/packages/terra-list/src/terra-dev-site/test/list/ListItem.test.jsx) from `terra-list` does not seem to have this issue when I tested it on Mobile Safari on an iPhone XS Max.

**Comment by christinelang** [comment]
@nramamurth, this was only happening on iPad for us. We will be uplifting to terra-list 4.x soon.

**Comment by StephenEsser** [comment]
@nramamurth 

The issue can be reproduced here using mobile safari:

https://engineering.cerner.com/terra-core/#/tests/terra-list/list/list-item

Steps:

1. Open the [link](https://engineering.cerner.com/terra-core/#/tests/terra-list/list/list-item) above in Safari on a mobile device. 
2. Click the list item labeled `row selectable`
3. Observe the row is now appearing in a hovered / focused state. 

The core of the issue is that mobile safari activates hover pseudo selectors when they are clicked on mobile.

Here is a reduced test case that demonstrates the issue on mobile safari. https://codesandbox.io/embed/0mxvp7402w

**Comment by nramamurth** [comment]
I now see what you are saying after playing around with different brighter colours on the [test page](https://engineering.cerner.com/terra-core/#/tests/terra-list/list/list-item). I was able to reproduce this issue on the following mobile browsers:

- Chrome 73.x 
- Safari 12
- Firefox 16

**Browser Bugs:**

There are bugs logged to Chrome<sup>[1]</sup> and Safari <sup>[2]</sup> around this issue.

[1] https://bugs.chromium.org/p/chromium/issues/detail?id=370155
[2] https://bugs.webkit.org/show_bug.cgi?id=158517

**Workaround (?):**

Upon further investigation, I found out that there is not really a very elegant workaround to fix this issue ourselves. A _**possible workaround**_ that is mentioned in an article<sup>[3]</sup> and an implementation<sup>[4]</sup> is to support hover styles only on non-touch devices (possibly **_only_** desktop browsers). 

More context: https://github.com/twbs/bootstrap/pull/13049

[3] https://humanwhocodes.com/blog/2012/07/05/ios-has-a-hover-problem/
[4] https://github.com/twbs/mq4-hover-shim/blob/master/src/browser/mq4-hover-shim.js

I then simply went ahead and audited the styles for `:active` and `:hover` to see if they could be distinguished in a better way so that the interaction looks better. 

https://github.com/cerner/terra-core/blob/f756445dd77a0718c2d403d29c29fce50fa90c93/packages/terra-list/src/List.module.scss#L95-L98

Unfortunately, `:active` does not really apply at all on Chrome and Safari on iOS according to the article [5]. 

> On mobile devices 📱, like the :focus pseudo-class, the :active pseudo-class applies on the tap of the element. And again, it doesn’t apply at all in the mobile Safari browser.

[5] https://bitsofco.de/when-do-the-hover-focus-and-active-pseudo-classes-apply/

I am not really sure if there is an elegant way to do it. @bjankord @neilpfeiffer @StephenEsser I'd like to have your input on this issue to further proceed. Thanks.

**Comment by bjankord** [comment]
Let's test wrapping the hover style in the following media query.
```css
@media(hover: hover) and (pointer: fine) {
 ```

e.g.
```scss
.is-selectable {
  @media(hover: hover) and (pointer: fine) {
    &:hover {
      background-color: var(--terra-list-item-hover-active-background-color, lighten(#ebf6fd, 2%));
    }
  }

  &:active {
    background-color: var(--terra-list-item-hover-active-background-color, lighten(#ebf6fd, 2%));
  }
}
```

**Comment by nramamurth** [comment]
@bjankord I had not tested it out because the specification<sup>[1]</sup> had tagged it as 'at risk', I'll anyways try it out and give an update. 

[1] https://www.w3.org/TR/mediaqueries-4/#hover

**Comment by nramamurth** [comment]
@bjankord 

Using the [media query suggestion](https://github.com/cerner/terra-core/issues/2076#issuecomment-481191000), here is what I noticed on the [test page]( https://engineering.cerner.com/terra-core/#/tests/terra-list/list/list-item).

**Chrome 73.x and Safari 12 on iOS:** `hover` styles are not applied upon tapping on a `list-item`. 

**Firefox 16 on iOS**: `hover` styles are applied upon tapping on a `list-item` but they are not sticky like they used to be sans the media query.

**Comment by nramamurth** [comment]
FYI the interaction media features are not supported on IE 11 and I could confirm it in-house.

**Comment by nramamurth** [comment]
@bjankord @ryanthemanuel Should we possibly hold up on this given that the media interaction feature are not available in IE yet?

**Comment by bjankord** [comment]
A potential media query we could explore using would be the following:
```
@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none), (hover: hover) and (pointer: fine) {
...hover styles here...
}
```

This should apply styles to IE browsers or browsers that support hover & pointer: fine.
