### ISSUE TITLE
Provide a way to remove the margin-bottom style from the Field of terra-form-field

### ISSUE THREAD

**Issue by mrw100** [cerner/terra-core#2134]
# Feature Request

## Description
We are using the terra-form-field with a terra-form-select and we noticed that there is extra margin being applied to the bottom of the field, which comes from the margin-bottom: var(--terra-form-field-margin-bottom, 1.428em); style.  As you can see from the attached screenshot this causes the field to be pushed up higher than our other controls in that section. We would like have the ability to disable this margin, so we can avoid overriding this with our own CSS.

## Additional Context / Screenshots
What's happening now (orange section is the margin we would like to remove):
![image](https://user-images.githubusercontent.com/1413706/50363701-6c994b00-0532-11e9-83af-3dc82bbf3ab5.png)

What we would like:
![image](https://user-images.githubusercontent.com/1413706/50363792-e0d3ee80-0532-11e9-92c0-a1bf42745d50.png)

**Comment by JakeLaCombe** [comment]
I saw this posted earlier, and I honestly think the solution for your particular instance is to create your own composed input of the dropdown and the button, then use the custom field to put both of them together. From looking at what you have, it feels like the button interacts with the dropdown, and that both should be apart of the same container. It will also help with accessibility as well, as users could potentially use the left and right arrows to scroll through the individual components.

**Comment by JakeLaCombe** [comment]
Now I can still see that we consider potentially dropping the margin and relying on a component such as the spacer to control it, but for your instance, I feel you have a rare use case for a custom input and field.

**Comment by mrw100** [comment]
I actually forgot to have the padding in between those buttons, so I can see where the confusion is coming from. However, those two controls don't actually have any interaction with each other. They just sit on the same line. 

This is what UX has in mind overall, so hopefully this clears things up:
![image](https://user-images.githubusercontent.com/1413706/50595680-0633f700-0e67-11e9-9172-8ebe28f84a2f.png)

**Comment by bjankord** [comment]
+1 for an option to disable bottom margin. A question I have is should `margin-bottom: 0;` be the default when `isInline` is set on the field or should we add a new prop to disable bottom margin?

**Comment by JakeLaCombe** [comment]
I'm also curious now on the placement of the view text itself. Should we adjust that as well in our field component?

**Comment by mrw100** [comment]
@JakeLaCombe There is actually a separate issue for aligning the text to the left
https://github.com/cerner/terra-core/issues/1608

**Comment by ryanthemanuel** [comment]
@mrw100 does this need to be a form field at all?  It seems like there is a lot that you're not really needing out of the form field.

**Comment by mrw100** [comment]
@ryanthemanuel this is what was recommended from our UX designer. I believe the idea was to use the form field, so we inherit the styling and accessibility of the label from terra

**Comment by neilpfeiffer** [comment]
Thanks @mrw100 - our suggestion is to not to affect/change the display of the terra-form-field to achieve this, but for your specific case to not use the terra-form-field at all. 

Since your usage is particular to the timeline toolbar (it is not the traditional series of multiple questions/answers presented in a form, which is what the current form-field was designed for), and since this input can't ever be invalid or required (and doesn't need the help-text or error-text) --- the recommendation is within your NavigationControls View component, to construct your own field for the toolbar rather than import terra-form-field. 

Our suggestion is to copy how Terra has constructed the raw html markup (wrapper, label, aria + attributes, inputs) within our [terra-form-field](https://github.com/cerner/terra-core/blob/master/packages/terra-form-field/src/Field.jsx), and how it generates final markup for 
any field combination like the [terra-form-select/lib/SelectField](https://engineering.cerner.com/terra-ui/#/components/terra-form-select/form-select/select-field) so that you will have the same screenreader accessibility, plus follow similar text size/weight styling for the label, but add your own styling for positioning to the left that accounts for i18n.

cc: @gerard-isdell
