### ISSUE TITLE
Add theming variable for show/hide component's background-color

### ISSUE THREAD

**Issue by mayurikini** [cerner/terra-core#2184]
# Feature Request

## Description
As of now, show/hide component's background-color is set as transparent. But if in future it is changed to something else, it will break us (as there is no theming variable). And hence, we want [show/hide component's background-color](https://github.com/cerner/terra-core/pull/1956/files#diff-13454e4441d8282933d245179d241dedR26) to be themable.

**Comment by ryanthemanuel** [comment]
@mayurikini according to UX this background-color will never change since it should always be placed on something that provides the actual color.  Thus, no themable variable is needed.  Is there a specific case you're worried about?

**Comment by mayurikini** [comment]
I was worried that if UX decides to change it to something else, they will break us. If UX **guarantees** that they will **never** change the color, then I am okay with closing this issue.

**Comment by StephenEsser** [comment]
I don't think there are any guarantees for immutable component color designs. But in the event there are changes they are usually hidden behind a major version bump that will protect teams and allow them to theme the new variables when they uplift to the next major version. 

In this example I think it is unlikely, but not impossible, for background color to change. But for theme variables it is often better to be reactive rather than proactive. 

Adding theme variables as they become necessary helps keep the complexity / redundancy down.

**Comment by bjankord** [comment]
We don't see the background-color being changed in the foreseeable future. If it does change, we'll release a major version bump for this package with and upgrade guide to help migrate to the new version without introduction breaking changes in your app unknowingly.
