### ISSUE TITLE
[Terra-Avatar] - Fall Back Icon(USER VARIANT) not coming up in case of Image load failure.

### ISSUE THREAD

**Issue by vaibhavmsv** [cerner/terra-core#2221]
# Bug Report

## Description
I am trying to load Terra-Avatar(2.6.0 version) component with Image, hash value and size props. 
In case of image load failure, the fall back icon user variant should come up.  Instead a Blank circle is coming up. If we dont use Image and initials as props, then the user variant is coming up. But in case of Image Load Failure, User Variant is not coming as fall back icon.

## Steps to Reproduce

1. Build an Avatar Component. 
<Avatar
        image={URL of image}
        hashValue={give hash value}
        size="0.6em"
      />
2. Make sure URL of image is invalid.
3. Now when we load that avatar component, User Variant will not be coming up as fall back icon. 

## Additional Context / Screenshots

![image](https://user-images.githubusercontent.com/18640970/52560678-199b9000-2e1f-11e9-874f-688490a7b2ca.png)

![image](https://user-images.githubusercontent.com/18640970/52560747-549dc380-2e1f-11e9-9008-f31ca9e89756.png)

![image](https://user-images.githubusercontent.com/18640970/52560767-61221c00-2e1f-11e9-84f4-fb08a822ce5e.png)

## Expected Behavior
User Variant should come up incase of image load failure.

## Possible Solution
Not Sure

## Environment

* Component Name and Version: terra-avatar and version is 2.6.0
* Browser Name and Version: Chrome 
* Node/npm Version: Node 8

**Comment by yuderekyu** [comment]
The icon renders correctly on fallback - the issue is that a color variant is not attached to avatar when an `image` is specified. The color variant styles control the `background-color` and `box-shadow` - because the icon is white, it appears to be missing. 

The fix is to change [this](https://github.com/cerner/terra-core/blob/master/packages/terra-avatar/src/variants/Avatar.jsx#L73) to set a color variant. This will also need to be done in the `Facility` variant. I'll issue a PR to address this.
