### ISSUE TITLE
Forms - Number Field

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-core#2237]
# Feature Request

## Description

Create a first class number input form field.

**Comment by supreethmr** [comment]
first class number input field can be created using HTML form input with having value `number` for type attribute. it can be like extension of terra-form-input along with additional props like 
  1. max : The maximum value to accept for this input
  2. min : The minimum value to accept for this input
  3. step : specifies the number intervals between min and max

in addition to terra-form-input number field will have up and down arrows to adjust the value as shown below. 

Before proceeding with Technical Design would like to clarify following things with respect to number field. 

I found that terra-form-input can be used as number field too by passing number as a value for type property as shown in this example of hookshoot : [Window Bound Hookshot - Attachment Margin in Px](https://engineering.cerner.com/terra-ui/#/components/terra-hookshot/hookshot/hookshot) here they [have used input field with number type](https://github.com/cerner/terra-framework/blob/986dc7e26ce7bc0fa1c1bf926213afedd5d02b07/packages/terra-hookshot/src/terra-dev-site/doc/example/HookshotExample.jsx#L118) the only difference would be the min and max property of number input so would like to know is this new number field is only for having min and max property..?  because for min and max property number input displays up and down arrow button on input field which is not consistent across the browser as listed below : 

1. up and down arrows displays differently in different browsers like shown below do we need to handle this to keep uniformity among the browsers or do we need to go with the default behaviors of browser.

   Chrome :  up and down arrows will appear when input receives focus 
<img width="146" alt="Screen Shot 2019-03-26 at 5 52 23 PM" src="https://user-images.githubusercontent.com/12869809/54996691-f8b68500-4fef-11e9-9775-3b1b8c8a552c.png">

  Mozila and Safari :  up and down arrows will display by always 
<img width="149" alt="Screen Shot 2019-03-26 at 5 45 40 PM" src="https://user-images.githubusercontent.com/12869809/54996371-1df6c380-4fef-11e9-9be8-31f8fefa6301.png">

  IE 11 and Edge :  up and down arrows will not be displayed for number inputs
<img width="141" alt="Screen Shot 2019-03-26 at 5 54 52 PM" src="https://user-images.githubusercontent.com/12869809/54996812-4b903c80-4ff0-11e9-8f2b-a03fd6f06ea2.png">

2. up and down arrow keys changes the value between given min and max value when we press it but this doesn't seems to work in IE (tested with IE 11) we might need to handle up and down key press manually to enable number input functionality.

Below are the Existing Issues of HTML number input that's need to be fix to keep the same functionality across the browser.

Google Chrome : 
	1. Allows character ‘e’ in numeric text box 

FireFox : 
	1. Allows non-numeric characters in numeric text box
	2. Doesn’t re-initialize to numeric value on click of down arrow and up arrow / on keyboard down
            and up key.

Safari :
	1. Allows non-numeric characters in numeric text box

Internet Explorer 11 : 
	1. Allows non-numeric characters in numeric text box
	2. Up arrow and down arrow is not displayed in numeric input
	3. Min and max value is not honered
	4. Value doesn’t changes on click of down arrow and up arrow / on keyboard down and up key
	5. Doesn’t re-initialize to numeric value on click of down arrow and up arrow / on keyboard down
            and up key

Edge : 
	1. Allows non-numeric characters in numeric text box
	2. Up arrow and down arrow is not displayed in numeric input

**Comment by bjankord** [comment]
Nice work on the research for this. Let's make the type attribute a first class prop on Input/InputField. We'll use that to allow people to set `type="number"` in Input/InputField. We're fine with the cross-browser variances of input[type="number"].

**Comment by supreethmr** [comment]
input (terra-form-input) has already got first class prop defined for it :[code](https://github.com/cerner/terra-core/blob/553a8db6ba8641cf37211698fdfaf747904071cf/packages/terra-form-input/src/Input.jsx#L58) and here is an existing example for input with type as number : [Window Bound Hookshot - Attachment Margin in Px](https://engineering.cerner.com/terra-ui/#/components/terra-hookshot/hookshot/hookshot) in this example Terra-input field has been used with inputAttrs props like : 

<InputField
      label="Attachment Margin in Px"
      inputId={getId('hookshotAttachmentMargin')}
      **inputAttrs={{ name: 'hookshotAttachmentMargin', type: 'number' }}**
      defaultValue={this.state.hookshotAttachmentMargin}
      style={{ width: '200px' }}
      onChange={this.handleInputChange}
 />

I think this would do meet the requirement of input number field mentioned above.

**Comment by supreethmr** [comment]
Do we require Type as first class prop in terra-input-field also..? 
By doing this consumer can directly set value for Type prop in input-field instead of adding it through inputAttrs. 

Got this thought while going through the issue #2283 where disabled is being added as first class prop for form-field components to resolve confusion among consumers.

**Comment by ryanthemanuel** [comment]
Yes let’s make type itself a first class prop.

**Comment by ShettyAkarsh** [comment]
@bjankord @ryanthemanuel Shouldn't we not handle the Min, Max  and step values through separate props for these controls when the type="number" ? 

And also why can't we have a separate new control for the number input built upon current form input field with form input field type hardcoded to 'number' always and along with above mentioned props ?.
