### ISSUE TITLE
Ability for multi-line display or pass a node to select control for options

### ISSUE THREAD

**Issue by kschuste** [cerner/terra-core#2254]
# Feature Request

## Description
We would like the ability to display more than 1 string of text to the Select control.  It only takes a string and we are appending any additional lines of text we want into just being 1 string.  We would like the ability to pass in our own type of node or multiple strings that would allow us to customize how the options display in the select control.

## Additional Context / Screenshots
An example of what we are looking for:
<img width="211" alt="screen shot 2019-03-04 at 9 25 43 am" src="https://user-images.githubusercontent.com/1711642/53743449-760f2f80-3e60-11e9-823c-a6c24164bc25.png">

**Comment by bjankord** [comment]
I think this needs some UX review. cc/ @neilpfeiffer 
I'm curious how the intended display of an option would look when the select is closed.
What happens if the Options share the same bold text.

For example, if the select dropdown looks like:

**Cerner Corporation**
Continuous Campus

**Cerner Corporation**
Innovations Campus

**Cerner Corporation**
Realization Campus

**Cerner Corporation**
Riverport Campus

**Comment by neilpfeiffer** [comment]
This needs addition discussion and clarity in how functionality & designs should work across all select variants (text in default/combo/search, pills in tag/multi, etc), plus api for how contents of the multi line displays might search/filter/match. 

Initial thought are Terra might offer example patterns of how to solve for multi-line displays with current api, then specific types of multi-line options (addresses, meds, providers) would be created as innersouce and shared.

**Comment by benbcai** [comment]
The goal here is to determine if terra-select can support showing the option display in multiple lines with minimal changes. It appears that this can be accomplished by setting the `white-space` css style to `pre-line`

@bjankord If we injected line breaks (`\n`) in the select option display to break the display into multiple lines, do you think that the full display would still be read out appropriately from an accessibility standpoint? The display would be constructed like this:


```
<Select
  id="pharmacy"
  placeholder="Select a pharmacy"
  variant="combobox"
>
  <Select.Option value="pharmacy1" display={"CVS Pharmacy " + '\n' + "123 Bannister St " + '\n' + "Kansas City, MO 64114"} />
  <Select.Option value="pharmacy2" display={"Walgreens" + '\n' + "     456 Nall Ave" + '\n' + "             Overland Park, KS 66213"} />
</Select>
```

![Screen Shot 2019-04-29 at 2 57 42 PM](https://user-images.githubusercontent.com/22618655/56923040-2ed3a280-6a8f-11e9-8ea2-21538481e369.png)

@neilpfeiffer If we decide to use the `white-space` style to accomplish this, do you think we should set it to `pre-wrap` to preserve all whitespaces (as in the Walgreen option above) or `pre-line` to collapse sequences of whitespace into a single whitespace? `pre-wrap` provides a bit more flexibility since it displays the text as is.

**Comment by neilpfeiffer** [comment]
@benbcai - I believe the best path forward (as was discussed in Terra Warroom a few weeks ago) with this request is rather than trying to solve for any number of multi-line option displays, (how they could possibly display in the list -- plus also need to display after being selected within the input) and trying to resolve how to adapt the current terra-form-select API, is instead to recommend that a brand new select control be built, exclusively designed for an address selection.

That way the options within the list can be well formed and have a constricted API, plus how the selected address needs to appear within the closed select will be designed/constrained specific for addresses, not needing to account for any number of multi-line displays, which most likely will each have their own very specific requirements. 

If I remember, we recommended keeping the issue open until the control has been built, most likely being internal to start, localized within the project requesting it for the immediate term. 

cc: @kschuste @ryanthemanuel @bjankord

**Comment by benbcai** [comment]
@neilpfeiffer The initial recommendation was to create a specific select control for this use case. We have met with the consuming team to discuss this recommendation. In the meeting we also discussed to explore if there is any quick change we can make to show the display in multiple lines. The ultimate plan might still be to create a new select component for this purpose in the future but the thought was that it would be a quick win for now if we could display in multiple lines even with no changes to the font styles.

**Comment by neilpfeiffer** [comment]
Thanks for the update @benbcai 

Next steps will then need to spike & explore the impacts of the recommended CSS changes, and the UI impact of injecting the additional new line characters in the display for when it shows in the input/"closed" select control, to see if a "quick win" might be possible or is too risky.

**Comment by benbcai** [comment]
## Spike
Below are code snippet and a gif showing the different ways of how the multiple line displays would look like in the dropdown menu and input when new lines are injected into the option displays. 

- By applying the `white-space` style to `pre-wrap` for the option display, new lines and white spaces in the dropdown menu are preserved as seen in the example below.
- If we prefer to collapse sequences of white spaces to a single space for each display in the dropdown menu, the `white-space` style can be set to `pre-line`.
- When a multi-line option is selected, all the text in the option will be displayed in the input.
- While both new lines and white spaces in the dropdown menu display are preserved, the new lines are ignored and only white spaces are preserved when an option is selected and displayed in the input.
- One drawback for allowing multiple lines in the option is that if the number of lines for each option is different, it may be less obvious to see the separation of each display at first glance until tabbing thru the menu items to highlight each option.

<img width="1285" alt="Screen Shot 2019-05-03 at 10 14 15 AM" src="https://user-images.githubusercontent.com/22618655/57147034-4c08b980-6d8c-11e9-820f-4760ad11b129.png">

![Select - After](https://user-images.githubusercontent.com/22618655/57147039-5034d700-6d8c-11e9-9702-2743ffbcedca.gif)
