### ISSUE TITLE
[terra-avatar] should allow non-square images

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#2259]
# Feature Request

## Description
Current avatar accepts images, but distorts the presentation unless the image provided is a perfect square. https://github.com/cerner/terra-core/pull/2224#issuecomment-469676287

Need to determine if terra-avatar should allow for non-square images to be handled such that they do not distort the image/photo provided. 

## Additional Context / Screenshots

<img width="271" alt="screen shot 2019-03-05 at 8 53 56 am" src="https://user-images.githubusercontent.com/1355485/53813933-52152200-3f24-11e9-9d11-48e0ec0f9413.png">

**Comment by yuderekyu** [comment]
@neilpfeiffer perhaps we only set `max-width: 100%`? This will scale the image to fit correctly without distortion.

**Comment by JakeLaCombe** [comment]
The one limitation I see with that is if you have an image that is wider than it is tall by a decent proportion. It would look very small in the avatar circle.

**Comment by pranav300** [comment]
The issue seems to get resolved by using the property `object-fit: contain`, But it is not supported by IE. So, for this to work in IE, Can we use polyfill https://github.com/bfred-it/object-fit-images. I used this and tested for IE and it works as expected.

Screenshot:
**IE11**
<img width="575" alt="IE11" src="https://user-images.githubusercontent.com/29273628/60098327-e2e16900-9772-11e9-8b95-d29497edce4c.PNG">

**Comment by neilpfeiffer** [comment]
I think we should use `object-fit: cover` instead of 'contain'  (uses the smaller of the two dimensions as the side to fit to, creates more cropping, but no background color bleed through), but that would be a good fix to the problem.

Next steps sounds like we need to evaluate the use of the polyfill and if anyone has any concerns. Thanks @pranav300
