### ISSUE TITLE
[terra-form-select] - Does not function correctly within a modal

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-core#2330]
# Bug Report

Starting with version 5.12.0 the default Select variant no longer works within the Modal Manager.

Initial assumptions are the Select attempts to shift focus into the dropdown menu, but is blocked by the focus trap of the modal manager. 

## Description

The Select (default variant) will not open when presented within a Modal Manager. Clicking on the Select will briefly flash, but the menu will not remain open.  

## Steps to Reproduce

1. Install a version of Select ^5.12.0
2. Add a Select (default variant) into the content presented by the Modal Manager
3. Launch the modal
4. Click on the Select. Observe it does not open.

## Additional Context / Screenshots

To improve the accessibility of the Select changes were made that shifts focus into the dropdown menu. This was done to make it easier to interact with the Select with screen readers.  

## Expected Behavior

The Select should open when displayed within a modal. 

## Possible Solution

1. Prevent the Select from shifting focus to the drop down. This may cause problems with accessibility.
2. Implement the request / release focus disclosure methods within the Select.

## Environment

* Component Name and Version: terra-form-select 5.12.0

**Comment by bjankord** [comment]
😞It is unfortunate the focus management added to select is conflicting with focus management in modal manager. I think we should add wdio tests to cover this since it has been as  reported bug and we'd want to avoid a regression once we have a solution.

In regards to possible solutions, I don't see preventing the select from shifting focus to the dropdown as a viable solution. This will break the accessibility work we just added.

I think we'll need to look into option number 2.

A 3rd option for the default variant that came to mind that would be accessible and avoid having to deal with implementing request / release focus disclosure methods within the Select would be to go back to [rendering a customized native select for the default variant](https://codepen.io/bjankord/pen/oOBaYv). This would likely require a major version bump. With this we could style an element that appears as the default variant select now, but when clicked, opens up a native select.

**Comment by bjankord** [comment]
Another idea that came to mind would be to rework how we trap focus in the abstract modal. Currently we use react-focus-trap which prevents focus on DOM elements that are rendered outside of the modal. 

This requires wiring up request / release focus props when we display content in modals that are rendered in modal but are technically rendered outside of the modal DOM because they are rendered in a portal (select dropdown, date picker popup).

If we replace react-focus-trap with the way we've been doing focus trap for things like [terra-overlay](https://github.com/cerner/terra-core/blob/master/packages/terra-overlay/src/Overlay.jsx#L46-L48), where we specify a root container and set aria-hidden on it when the modal is open, this could fix the issue with select and no longer require needing to manage requesting and releasing focus when rendering components in a portal from the modal.

In the DOM, this would look something like the following.

Regular DOM, modal not open:
```html
<div id="root">
  <div id="my-react-app">app code</div>
</div>
```
When a modal is open, the DOM would change to following, allowing focus to move through content only in the modal.
```html
<div id="root" aria-hidden="true">
  <div id="my-react-app">app code</div>
</div>
<div>modal rendered in portal outside of #root</div>
```
When a modal is open and a select is opened, the DOM would change to following, allowing focus to move through content only in the modal plus the select content.
```html
<div id="root" aria-hidden="true">
  <div id="my-react-app">app code</div>
</div>
<div>modal rendered in portal outside of #root</div>
<div>select rendered in portal outside of #root</div>
```
Similarly, when a modal is open and a date picker is opened, the DOM would change to following, allowing focus to move through content only in the modal plus the date picker content.
```html
<div id="root" aria-hidden="true">
  <div id="my-react-app">app code</div>
</div>
<div>modal rendered in portal outside of #root</div>
<div>date picker popup rendered in portal outside of #root</div>
```
