### ISSUE TITLE
[terra-table] add border-bottom prop to support mpagestyle theme on subheaders

### ISSUE THREAD

**Issue by kc4181** [cerner/terra-core#2461]
# Feature Request

## Description
Need to add a border-bottom prop on table subheaders to support the mpage theme

## @ Mentions
@neilpfeiffer

**Comment by supreethmr** [comment]
terra-table Sub-header not receiving styles of [.subheader class](https://github.com/cerner/terra-core/blob/a44308d6f54f6042e6ca969e503b9069740bd8c4/packages/terra-table/src/Table.module.scss#L92).

This could be due to `subheader` class is assigned only to `<td>` element in [TableSubHeader.jsx](https://github.com/cerner/terra-core/blob/a44308d6f54f6042e6ca969e503b9069740bd8c4/packages/terra-table/src/TableSubheader.jsx#L27) 
```
  <tr data-terra-table-subheader-row>
    <td {...customProps} className={cx('subheader', customProps.className)} colSpan={colSpan}>
      {content}
    </td>
  </tr>
```
instead of `<tr>` element. 

hence border-bottom style changes are not reflecting for terra-table as shown below : 
<img width="1680" alt="Screen Shot 2019-07-03 at 12 43 01 PM" src="https://user-images.githubusercontent.com/12869809/60571632-9f4db700-9d91-11e9-9998-dc4e902e9818.png">

and after adding class `subheader` to `<tr>` element(sub-header row) border-bottom changes were reflecting in terra-table : 
<img width="1474" alt="Screen Shot 2019-07-03 at 2 51 02 PM" src="https://user-images.githubusercontent.com/12869809/60580052-04a9a400-9da2-11e9-90b8-cce282b4f54f.png">
