### ISSUE TITLE
[spike] - Investigate using react-docgen to generate markdown version of props-table

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#2513]
# Feature Request

## Description
We are looking at updating our usage of react-docgen from a client-side usage to a build-step usage to reduce the bundle size of our documentation site.

With this, we want to look at if/how we can use react-docgen to generate markdown files of the props table for components. We'd then pipe these into the doc pages. The main focus of this spike is figuring out how we might go about generating the prop tables as markdown files via react-docgen.

Importing the markdown files into the docs is not so much of a concern of this spike.

**Comment by supreethmr** [comment]
Hi @amichaelparker, 

After this code changes are merged we are getting below errors on our internal theme repos (Cerner-Clinical-Theme, Orion-Fusion-Theme) :  
<img width="1541" alt="Screen Shot 2019-09-09 at 5 07 53 AM" src="https://user-images.githubusercontent.com/12869809/64522856-a11b8580-d2c0-11e9-98f8-a70d8ede243e.png">

Master build is failing with same Error : https://jenkins.cerner.com/ion/blue/organizations/jenkins/terra-internal%2Forion-fusion-theme/detail/master/101/pipeline/ 

I assume this error is due to the `terra-props-table-loader` which is defined within scripts folder in terra-core. Theme Repos not able to resolve path for `terra-props-table-loader`. 

cc : @bjankord
