### ISSUE TITLE
[terra-avatar] Allow Fallback to Initials Display

### ISSUE THREAD

**Issue by RLRickard** [cerner/terra-core#2559]
# Feature Request

## Description
Currently, the image fallback logic of the avatar displays a generic icon. However, this fallback does not differentiate between different 'Avatars' if multiple images fail to load.
If the image fails to load and initials are provided - the avatar should fallback to the initials display instead (or at least be optional).

**Comment by bb3284** [comment]
This may be a blocker to our consuming Terra Avatar in Connect.

**Comment by yuderekyu** [comment]
That makes sense to me, but this needs UX input. UX requirements specify that if the photo fails to load, a generic icon is used. If a photo is not provided, initials are used.

cc @neilpfeiffer

**Comment by neilpfeiffer** [comment]
I did some initial tests, and although the current logic for avatar seems to follow UX recommended pattern to have the fallback in place to do:
` image (if/provided || is not invalid) > initials (if provided) > generic icon`
when reading the current code:
https://github.com/cerner/terra-core/blob/9109b5b59b836d65ec48a2c533de5ceb582bfd8a/packages/terra-avatar/src/variants/Avatar.jsx#L88-L95

...however, doing a quick check and adding initials on our current [Invalid Image test](https://engineering.cerner.com/terra-core/tests/terra-avatar/avatar/avatar/invalid-image-avatar) 
it does not honor the initials. I also was able to break it by giving the image non-image file types, so we may need to spike to see if we are properly handling fallbacks in general.


\.
>  the avatar should fallback to the initials display instead (or at least be optional).
The option to fallback to initials should be including the prop or not.

\
\
@RLRickard I'm not quite sure what you mean by 
> this fallback does not differentiate between different 'Avatars' if multiple images fail to load.

If you could better explain what you meant by that, since a single User Avatar should only receive one image. And the Facility avatar only has the fallback to the icon, no initials. Do you mean if multiple avatars on a given view all are failing to load (broken service, etc.) that they collectively have a fallback? Or please better explain, Thanks.

**Comment by RLRickard** [comment]
@neilpfeiffer - I meant that if multiple avatars in the same view fail to load, that they all show the same generic icon instead of the User's initials when that data is available.

**Comment by neilpfeiffer** [comment]
Thanks @RLRickard, that's what I assumed you meant, how a field/list of avatars with failures could appear all similar even with the individual colors. Adding the 'bug' tag so we can correct fixing the initials to display as primary fallback when provided.

Special Implementation note for others implementing Avatar: unless your design team has given you special instructions to have the avatars all have the same color or specific color, it is recommended that the full person's name be provided as the `alt` prop, and providing a UserID, GUID, MRN or other common identifier as the `hashValue` will keep the avatar color consistent across multiple applications.

**Comment by neilpfeiffer** [comment]
Blocking -- awaiting final OCS direction to change the API for the fallback from Image > Initials (> Icon) and then changing the Shared User to a Generic with variants.

**Comment by bb3284** [comment]
Please escalate the design on this issue.  CareAware Connect needs this completed in order to be able to consume Terra-avatar which is required as part of our OCS project.

**Comment by jeremyfuksa** [comment]
**Design Update:**

After some discussion, here is how we need to move forward with avatar:
The `initials` prop becomes required. The icon fallback example is not necessary for the documentation.

![fallback-plan](https://user-images.githubusercontent.com/726351/63621660-1ea17f00-c5ba-11e9-9741-6f01ed7cc7fa.png)

Then, the `sharedUser` variant becomes the `generic` variant with a new `iconType` prop that can be `single`, `multi`, or `provider`.

![generic-avatar](https://user-images.githubusercontent.com/726351/63621794-7dff8f00-c5ba-11e9-8879-8632cdc2c46e.png)
---
**Code Updates:**

**[terra-avatar] src/common/AvatarUtils.jsx**
- [ ] Change shared user variant to generic [#L11](https://github.com/cerner/terra-core/blob/966148a89651731a4120cb58069773b7b84c9106/packages/terra-avatar/src/common/AvatarUtils.jsx#L11)

**[terra-avatar] src/common/Avatar.module.scss**
- [ ] Verify provider icon has been added from #2026

**[terra-avatar] src/variants/SharedUser.jsx**
- [ ] Becomes `Generic.jsx`
- [ ] Add `iconType` prop as `oneOf['single', 'multi', 'provider']` and make required [#L11](https://github.com/cerner/terra-core/blob/966148a89651731a4120cb58069773b7b84c9106/packages/terra-avatar/src/variants/SharedUser.jsx#L11)

**[terra-avatar] src/variants/Avatar.jsx**
- [ ] Make `initials` prop required [#L33](https://github.com/cerner/terra-core/blob/966148a89651731a4120cb58069773b7b84c9106/packages/terra-avatar/src/variants/Avatar.jsx#L33)
---
**Theme Updates:**

Provider icon will need to be verified in all themes
- [ ] cerner-clinical-theme, cerner-consumer-theme, ti-clinical-lowlight-theme, orion-fusion-theme

**Comment by supreethmr** [comment]
Just Curious to know about design before Implementation. 
why do we need to keep initials prop as required. we can still add fallback to initials when it is provided and if it is not provided then we can still fall-back to default user Icon.

**Comment by bjankord** [comment]
We should try to group the release of this with https://github.com/cerner/terra-core/issues/2026

**Comment by jeremyfuksa** [comment]
> while we can add the fallback to initials without making it as required only on when it is provided and fall-back to default user Icon when it is not provided.

That works for me. Go ahead and ignore the required suggestion.

**Comment by jeremyfuksa** [comment]
@neilpfeiffer and I were discussing, and the initials _do_ need to be required because we're moving the icons into the generic variant of this component. So, the standard avatar is either initials or an overlay image. There is no icon fallback.

So, this raises a new question: What should the standard variant do when sending the initials fails? Of course, if there's a complete failure of the service to send data, that's just not going to render anything, but what if the initials are malformed (e.g. > 2 initials)?

Does the avatar render as a blank color circle? Or does it not render? The designer in me says that the blank circle at least keeps consistency with any other avatars in a list, but not rendering it would at least make it obvious that something went wrong. Is there a precedent with other components that would guide this decision?
