### ISSUE TITLE
Alert component does not wrap content when there is not enough space to display it all faceup within a container

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#2603]
# Bug Report

## Description
This issue can be seen with the following code:

```
<div style={{width: '50px'}}>
  <Alert type="alert" title="TEST" />
</div>
```

The text, "TEST" is clipped off out of view when rendered within this div.

## Steps to Reproduce

1. Set width on container that doesnt allow for full width of Alert to be displayed
2. Add alert component to it that overflows the width of the parent

## Additional Context / Screenshots
Screenshot of expected alert
<img width="148" alt="Screen Shot 2019-08-21 at 10 28 45 AM" src="https://user-images.githubusercontent.com/633148/63445733-86ab6600-c3fe-11e9-90d9-2dc1a0f7202c.png">

Screenshot of buggy alert
<img width="54" alt="Screen Shot 2019-08-21 at 10 28 29 AM" src="https://user-images.githubusercontent.com/633148/63445744-8ca14700-c3fe-11e9-8833-ab1d3472e6ea.png">
Text is clipped out of view

## Expected Behavior
The terra alert component handles text wrapping / content overflow appropriately when placed within a container with a set width.

## Environment

* Component Name and Version: terra-alert

## @ Mentions
@dkasper-was-taken

**Comment by pranav300** [comment]
I think we have to change the layout as the width 50px doesn't have space required for text. 
<img width="108" alt="alert" src="https://user-images.githubusercontent.com/29273628/63749153-7432a000-c8c8-11e9-8f0d-2cba1011acc9.PNG">

What we can do is add ellipsis for the text or use tooltip over the icon so that if the space for text is less we can hover over the icon for the message to appear. @neilpfeiffer What do you think?

**Comment by pranav300** [comment]
@neilpfeiffer This is the solution which I have come up with after looking into notification dialog. What do you think about it?

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/29273628/63832112-bf62b680-c98d-11e9-89b1-2392c8e4527a.gif)

**Comment by pranav300** [comment]
Had an offline conversation with @neilpfeiffer:
>Generally forcing internal side scrolling when a view is reduced past it's intended minimum is not a pattern we would recommend as a resolution. I'm not so sure that the component needs fixing but need to look further.

**Comment by neilpfeiffer** [comment]
Removing `Blocked: UX Input Needed` label since `Needs Investigation` and `Needs Design Input` already cover work UX needs to do first.

Alerts are not designed/intended to be used at sizes less than a full-page container, so for mobile screen equivalent is at least 320px+ width. So  any usecase and page construction that is causing this scenario also needs to be re-examined and re-built to not create this scenario.

Marking as `priority:low` since the component could add a methodology to handle, but is not a critical item to resolve.

**Comment by benbcai** [comment]
I'm removing the `bug` label since displaying the alert at such a small width is not the intended or expected use case and such edge case should be resolved by other means.
