### ISSUE TITLE
[terra-form-select] - Internal state is wiped away when the variant switches

### ISSUE THREAD

**Issue by mananarora** [cerner/terra-core#2645]
# Bug Report

## Description

Currently user input within the select field is being wiped out when it reaches 249 characters  after version bump from 5.11.0 to 5.29.0 as we're changing the variant from tag to multiple when characters length reaches 249.

## Additional Context / Screenshots
Here in the ppt I've attached a video and reduced the character limit to 4 from 249.
[Presentation.pptx](https://github.com/cerner/terra-core/files/3614850/Presentation.pptx)

## Expected Behavior

Ideally it should throw a warning as soon as it reached the character limit we set but in place of warning, user input in select field is getting wiped out.

## @ Mentions

@StephenEsser 
@nramamurth

**Comment by nramamurth** [comment]
Just so that the context is not missed out, here is a reduced test-case that I had put together earlier based on an internal Teams discussion to help troubleshoot the issue further. 

```
import React, { useState } from 'react';
import Select from 'terra-form-select';

const MAX_LIMIT = 2;

const MyApp = () => {
  const [value, setValue] = useState([]);
  const [showLimitExceededError, setShowLimitExceededError] = useState(false);
  const [variant, setVariant] = useState('tag');

  const handleSearch = (searchValue) => {
    const showError = searchValue && searchValue.length > MAX_LIMIT;
    setShowLimitExceededError(showError);
    setVariant(showError ? 'multiple' : 'tag');
  };

  return (
    <Select
      id="search"
      onChange={setValue}
      onSearch={handleSearch}
      placeholder="Select a color"
      value={value}
      variant={variant}
      noResultContent={showLimitExceededError ? (<div>ugh, error</div>) : null}
    >
      <Select.Option value="blue" display="Blue" />
      <Select.Option value="green" display="Green" />
      <Select.Option value="purple" display="Purple" />
      <Select.Option value="red" display="Red" />
      <Select.Option value="violet" display="Violet" />
    </Select>
  );
};

export default MyApp;
```

@mananarora 

This is heads-up: Please provide detailed steps to reproduce the issue and reduced code sample (_always helpful_) when you log requests in the future 🙃

Does the above example match with your implementation?

**Comment by mananarora** [comment]
Yeah the example matches with our implementation.

**Comment by nramamurth** [comment]
Porting the initial investigation from Teams based on the scenario @mananarora put forth - 

"I haven't dug further but what I notice is that [getDerivedStateFromProps](https://github.com/cerner/terra-core/blob/master/packages/terra-form-select/src/multiple/Menu.jsx#L151-L180) in Multiple variant is not hit upon updating the variant from 'tag' to 'multiple' immediately and hence I obviously don't see the `noResultContent` at this point. 

The reason that I see it upon copy paste immediately after that is that - at this time, the 'multiple' variant has already rendered successfully and its `getDerivedStateFromProps` would have already executed fine which means that I see the `noResultContent`."

**Comment by nramamurth** [comment]
I think it is worth involving @ryanthemanuel @bjankord @StephenEsser and @dev-cprice in this discussion to know whether the way Select is being revamped, variant switching could be accommodated with the current design.

**Comment by StephenEsser** [comment]
With the recent changes to split the Select variants out into individual component files I do not believe that variant switching is possible anymore. The Select is acting as a switch to map a variant to a component. When the variant switches a new component is swapped in, destroying any previous uncontrolled state. In this case the text input and filtered option state.

If we can narrow down the use-cases and expected behavior consumers are relying on during variant switching we may be able to integrate that behavior into the individual variants and remove the need to switch variants. 

For example, some consumers are switching between multiple and tag variants when they want to enable and disable free text entries. An `allowFreetext` prop to enable / disable this behavior in the tag component might satisfy this use-case. ( Or possibly a max-length on the free text entry )

As consumers run into this issue I recommend they document the behavior they are expecting and the behavior they are trying to achieve on this issue so it can be evaluated to determine if it is both a behavior terra can implement and a behavior terra wants to support.

For additional context here is the email thread I sent to Manan asking him to log this issue. 

> Hi Manan,
 
> The Select has undergone significant internal implementation changes that swap out the underlying component structure when the variant changes. Unfortunately I do not see an easy solution to resolving the issues you are facing.

> In the short term you can delay upgrading and log an issue to the terra-core repository. I recommend documenting the previous behavior but more importantly targeting the specific functionality that you believe is necessary for the Select to support.  

> The variant switching is an uncommon behavior but one I think a few consumers have relied upon. Ideas for integrating similar behavior into the individual variants would be beneficial. ( IE: Ability to disable free-text entry for Tag when necessary, ability to customize the dropdown content to display an error message, etc… )

> The direction the Select is heading now does not look promising for variant switching. The Select is moving towards a more rigid implementation. Some of those discussions can be found here: https://github.com/cerner/terra-core/issues/2492

**Comment by prmeznar** [comment]
> As consumers run into issues regarding variant switching I recommend they document the behavior they are expecting and the behavior they are trying to achieve on this issue so it can be evaluated to determine if it is both a behavior terra can implement and a behavior terra wants to support.

The Orion Orders team has run into the same issue. In our use case we're swapping between the search and combobox variants, but I think the root goal is the same - controlling what sort of values can be added. For us, we want to allow numbers (we prepopulate the dropdown with suggested values, which is why we're using a Select vs Input) but not text, and we're achieving this through swapping to a search box when we notice invalid input entered (and then displaying help text in the NoResultsContent).

We'd have to check with UX for what ideal behavior would be - I think our current approach was identified as a workaround, but one we were pretty happy with as it was similar to some of our other workflows with straight search variants.

We also have components where we've added custom logic to block invalid input, but this couldn't be replicated in the Select box as we couldn't 'listen' and reject the input before it appeared in the select box. Personally I find letting the user type but just not add the value a better experience than blocking them from putting that input - except in cases where the reason they are blocked is pretty obvious (e.g., date time components).

**Comment by PolymorphedSquirrel** [comment]
As a user of the variant switching, my team relied heavily on this to get some very specific functionality back out of the select.  The specific units of functionality that are key to maintaining the behavior requested by our design team are the ability to display some message to the user when they go over a certain number of characters (attempting to make a free-text entry).  This was done due to having no good way to hard limit the user's input length.  We also attempt to short circuit much of the logic around placing freetext entries into the dropdown, and will not place them as written by the user. (prepending text to indicate that the selection made was not a prederterming choice in the list).

Our usage of the variant switch was mainly due to a need allow freetext, but place limitations on what the user can place inside the select.  We accomplished this in the past by switching from a single with freetext or multi with freetext into a non-freetext capable variant and using the No Results Found node of the Select to display our custom message regarding input length.  We also avoided the risk of any re-renders or information flashing up temporarily due to the Select's internal state reflecting a change that our redux store would not allow in the value we wish it to hold (either disallowing the input entirely or prepending indicator text to free text entries). This is also imperative for a clean experience with a unique select type that our application uses where the first entry in the list disallows any other selection or freetext entry when selected. I understand that it sounds quite crazy, but in the use case we have, this behavior is delegated to a response that is mutually exclusive to all other possible responses as indicated by backend content.

Given that the internal state is now cleared out with the update to break apart variants from a structural perspective, this behavior does not seem possible at first glance.  Potentially this could be avoided by allowing a prop-driven behavior switch as @StephenEsser mentioned above.  Maximum free-text input length and/or allowing for cutting the capability on or off from the consumer's side would work here.  We could also need to evaluate some way to give visual feedback to the user, preferably capable of supporting UX asks directly by rendering a passed node or defaulted to something sane when a character limit is set, but no node given to display upon attempting to break the limitation.  Maybe a "Character limit of X cannot be exceeded" type of display within the dropdown portal?

Another alternative, would be allowing the consumers to pass in a string to the Select that allows for prepopulation of characters into the input.  This would circumvent portions of the variant switching issues that know of currently. The search string is readily available in the onSearch callback, so there is a fairly easy way for consumers to stay constant in sync with entries in real time. Admittedly, this comes with a downside that the end user will not be aware that the pre-populated text is not actually an entry if a page were to be loaded and prepopulate a string into a single select.

I've started some conversations with my design team to get their thoughts on what our best path forward is, and hopefully can bring their input back to the discussion soon.  In the mean time, I think these are relatively reasonable ideas to toss around that could maintain functionality for terra consumers that has gone down this path of squeezing out extra functionality from the component beyond the normal use cases.

**Comment by bjankord** [comment]
Talked about adding onSearch to the field to allow more control for users using the controlled component.

**Comment by StephenEsser** [comment]
Adding a few example solutions.

1. Allow the combobox / tag variants to disable free-text entry and provide a message within the dropdown.

Notice the add button gets removed when the character length exceeds 10 characters and a message is displayed in the dropdown.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6720991/65349514-2f3d1900-dba9-11e9-9e56-4117bc048831.gif)

2. Expose an onChange prop for the input. Developers can reject or accept changes.

Notice that only numbers are being allowed to be entered into the input. Alpha characters are being typed but are being rejected. This keeps the add option permanently available, but rejects certain user input.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/6720991/65349560-55fb4f80-dba9-11e9-93cc-01083363fea1.gif)

3. Allow the user to enter an invalid value, but place the component into an invalid / error state when this happens.

Notice the user is allowed to accept the response with the add action. The error state and message is updated after the response has been added and the dropdown menu closes.

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/6720991/65349598-6f040080-dba9-11e9-9e4b-6eba349435d9.gif)

**Comment by avinashg1994** [comment]
IMO, the second solution provided by @StephenEsser _"To expose the onChange prop for the input"_ would be more apt, since it will provide more customisability to the consumers to filter or manipulate content as per their requirement and can also be used to cover a large number of scenarios for which they would require to switch the variant.
The only drawback with this approach is that "ComboBox / TagSelect" will not have a way to display an error/invalid message unless we provide an option to specify a message within the dropdown.

---

Also, I have a query regarding the first approach _"To allow the combobox / tag variants to disable free-text entry and provide a message within the dropdown"_. If we do go ahead with this approach, then will it not destroy the purpose of having different variants. i.e. The **combobox** variant can be configured to be like **searchSelect** and similarly **tagSelect** can be configured to be like **multiSelect** ?

---

On a side note, i noticed that the documentation for **"combobox and singleSelect"** shows `noResultContent` as prop, but i do not see it being used anywhere.
Should the documentation be upgraded ? **_'or'_** Is it intentional for the purpose of future enhancement ?
