### ISSUE TITLE
[terra-action-header] props to add custom icon to ActionHeader

### ISSUE THREAD

**Issue by tarunkolla** [cerner/terra-core#2907]
# Feature Request
I'm from Video platform team part of Platform engineering and we currently working on customizing [terra-action-header](https://engineering.cerner.com/terra-ui/components/terra-action-header/action-header/action-header) with [terra-collapsible-menu](https://engineering.cerner.com/terra-ui/components/terra-collapsible-menu-view/collapsible-menu-view/collapsible-menu-view) and wanted to add a custom icon to terra-action-header

#### Current Implementation:

*Css file:*
```
.header-icon {
 order: -1;
 margin: auto 0;
 padding: 0.28571em 0 0 0.71428em;
}
```

*js file:*
```
 <ActionHeader title={title}>
   <React.Fragment>
     <div className="header-icon">{terra-icon}</div>
     <CollapsibleMenuView />
   </React.Fragment>
 </ActionHeader>
```

## Description

Adding an icon to `ActionHeader` isn't something terra supports, it would be helpful to have this feature as a part of terra to make sure the solution will continue to work long term.

#### Example implementation: 
```
<ActionHeader icon={terra-icon} title={title}> 
  <CollapsibleMenuView />
</ActionHeader>
```

## Additional Context / Screenshots

This icon represents the state of the visit. 

We have a couple of places that we would be using this action header. Most of our solution would include having this ActionHeader with an icon that would be themed according to the state of a video visit between the provider and the patient.

Please take a look at the screenshots below: 

Example 1:
![Screen Shot 2020-03-17 at 12 37 43](https://user-images.githubusercontent.com/35357999/76884736-24a7c780-684c-11ea-9beb-832951d2284f.png)

Example 2:
![Screen Shot 2020-03-17 at 12 48 37](https://user-images.githubusercontent.com/35357999/76885753-bb28b880-684d-11ea-8a33-21f2db8f2061.png)

## @ Mentions

Including @nramamurth one of my teammates.
Including @tbiethman as we had a talk about this on Microsoft teams.

**Comment by nramamurth** [comment]
cc / @neilpfeiffer

**Comment by neilpfeiffer** [comment]
Thanks for your request @tarunkolla, this is not a design pattern that UX will be looking to add to the action-header component, which is intended to be pretty restricted in it's design, plus we will be updating to be even more restricted in the future (the only icon/button with is allowed to be on the left will be a back arrow button). 

There is nothing inherently bad/wrong with your design that shows the video visit state status as a key indicator, it is just not a widely used pattern that has been adopted elsewhere and formalized for others to use as well.

In the absence of having a dedicated designer, I would recommend you can achieve either one of two ways: make your own header based on your design pattern, or use the current terra-clinical-header with a defensive size wrapper around the collapsible-menu-view to have a max-width and percentage-based width applied, because unlike the action-header, the older clinical-header has a older/bad layout approach and the buttons on the right and left take flex priority over the text in the middle, and the collapsible-menu-view will never collapse, prior to completely covering the header text on small viewports (which truncates and does not wrap like the action-header). So some additional style will be needed and some testing based on the length of your header text to see what would create an appropriate responsive behavior that does not truncate the text at any breakpoint.

Your approach listed above setting the flex-order within the current action-header is creative, but completely not-supported and will break very very easily and would not be recommended.

**Comment by neilpfeiffer** [comment]
Closing as not a UX supported request.
