### ISSUE TITLE
Ability to Distinguish keyboard events vs Mouse click events on Terra-Search-Fields

### ISSUE THREAD

**Issue by Dinesh94Singh** [cerner/terra-core#2953]
# Feature Request
Distinguish keyboard events vs Mouse click events on Terra-Search-Fields / Ability to prevent calling onSearch when keyboard events take place.
## Description

Support for distinguishing mouse click vs keyboard events. We currently have a requirement to open up a modal when clicked on the magnify glass icon. When doing so, it should open up a modal for us. The issue we are seeing is with terra-search-field calling onSearch with text results upon hitting Enter keyword.

Additional talks with terra - https://teams.microsoft.com/l/message/19:772d6463a4cd4c65a1bf0198612d2543@thread.skype/1588609927653?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1588609927653&teamName=Terra&channelName=Feature%20Requests&createdTime=1588609927653
## Additional Context / Screenshots

Please refer to the team's chat's video to see the workflow, the file is too big to upload here.

## @ Mentions

@StephenEsser

**Comment by neilpfeiffer** [comment]
Closing as Not Supportable Feature Request:

Terra does not want to have different interaction options based on input mode for the search input. This component intentionally has the UI redundancy of the Enter and the Search Icon button performing the same action per requirements from Human Factors as specified in the [Cerner UX 
Design Standards](https://wiki.cerner.com/display/UserExperience/Search
):
> The user's search query will be performed when the users hits 'enter' or selects the search button.

\
@Dinesh94Singh Based on your video - it seems that you are trying to re-create the Windows search dialog pattern (searchable text input beside a [...] button), so without having a full component design already vetted, the initial UI recommendation would be to alter your component construction to use an additional button to explicitly launch the "full search/scan" modal and leave the search component functionality as is, rather than trying to repurpose the button within the search. Sample UI would be like this:
<img width="670" alt="Screen Shot 2020-05-08 at 9 35 39 AM" src="https://user-images.githubusercontent.com/1355485/81418177-ddcea380-9111-11ea-802a-280fda76a8fd.png">

This particular interaction pattern most likely should be it's own new component if it will be broadly needed, so feel free to work with your UX Designer to have it requested to get it in the backlog.
