### ISSUE TITLE
[terra-form-select] On mobile, the Select with combo/multi variant has inconsistent behavior

### ISSUE THREAD

**Issue by PaulSolDev** [cerner/terra-core#2964]
# Bug Report

## Description

On mobile: A select with a variant of combo or multi has varied behavior around keyboard focus for text entry depending on browser.

**Safari/Edge: expected behavior**

- Select dropdown arrow for the select (dropdown opens)

- Tap on the input (keyboard appears and input gains focus/text entry supported)

**Firefox/Chrome: bug** 
Scenario 1-

- Select dropdown arrow for the select (dropdown opens)

- Tap on the input (no response)

- Select on option in the dropdown (option selected, keyboard appears, and input gains focus/text entry supported)

Scenario 2-

- Select the input for the select (dropdown opens, keyboard appears, input gains focus/text entry supported)

## Environment

* Component Name and Version: Select
* Browser Name and Version: mobile Firefox and Chrome
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile): iOS 13.4.1

## @ Mentions

@StephenEsser

**Comment by lokesh-0813** [comment]
I have a few questions. 

1. Was this issue created based on testing in desktop browsers set to responsive mode? Because the behaviour is consistent across all browsers when you test on an actual mobile device. And the behaviour does not match the expected behaviour and is explained in point 2.

2. This [PR](https://github.com/cerner/terra-core/pull/2904) defends the expected behaviour defined in the issue. It was deliberately made to not give focus to input when clicked and show keyboard when dropdown is opened via arrow.

**Comment by PaulSolDev** [comment]
This issue was created based on testing on an iPhone Xr using the indicated browser apps.

I believe the intended behavior should be reviewed by UX.

**Comment by StephenEsser** [comment]
There are observable differences between variants on mobile browsers. Specifically between the combobox and tag/multi-select variants. The tag/multi-select variants are unable to allow focus on the input field if the dropdown was opened using the arrow. The combobox allows focus to be shifted to the input field when opened using the arrow.

Steps to reproduce the differences and issue:

Combobox:

1. On a mobile device navigate to https://engineering.cerner.com/terra-ui/components/terra-form-select/form-select/combobox.
2. Click the arrow of the first example to open the dropdown.
3. Click the input/placeholder text.
4. Observe the input receives focus and the keyboard opens

Multi Select:

1. On a mobile device navigate to https://engineering.cerner.com/terra-ui/components/terra-form-select/form-select/multi-select.
2. Click the arrow of the first example to open the dropdown.
3. Click the input/placeholder text.
4. Observe the input does not receive focus and the keyboard does not open

This [PR](https://github.com/cerner/terra-core/pull/2904) was intended to correct blur events firing from the Select. Prior to this fix the onBlur event would inconsistently fire even though the Select was not losing focus.

The multi-select being unable to allow filtering if opened via the arrow seems like a bug. It prevents a user from being able to filter the options even though there is an input and is inconsistent with the behavior of the combobox.

**Comment by lokesh-0813** [comment]
The issue is not specific to mobile browsers. Its across all platforms but is unnoticed in desktop browsers until debugged.

The issue in Multiple/Tag variant arises with the introduction of `pointer-events:none` for input box in this [PR](https://github.com/cerner/terra-core/pull/2270).

**Comment by lokesh-0813** [comment]
I have a question for UX. @neilpfeiffer what is the expected behaviour for multi/tag variant terra-form-select when we have a selected option and dropdown closed.

Current behaviour: 
When we have selected a option the placeholder is hidden.

![image](https://user-images.githubusercontent.com/16148882/85319469-2cc47280-b4df-11ea-833e-26f0d8e403bc.png)


Shouldn't it be something like this ? :
![image](https://user-images.githubusercontent.com/16148882/85319815-bf651180-b4df-11ea-9e8d-c8c216be0a53.png)

cc : @StephenEsser

**Comment by StephenEsser** [comment]
I believe the original design intentions only display the placeholder when no options are selected. 

![image](https://user-images.githubusercontent.com/6720991/85320397-9c5b4300-b488-11ea-8ac8-922c84ea56d5.png)

The input and placeholder will newline content if options are already selected:

![image](https://user-images.githubusercontent.com/6720991/85320337-8a79a000-b488-11ea-9fea-16b58e62cb6a.png)
