### ISSUE TITLE
[terra-action-footer] Text in footer doesn't wrap in ie 10

### ISSUE THREAD

**Issue by JacksonJN** [cerner/terra-core#3009]
# Bug Report

## Description

When using the terra `Text` component inside the terra `ActionFooter` component, the text doesn't wrap properly in internet explorer 10. Issue still occurs when `isWordWrapped` prop on `Text` component is set to true.

## Steps to Reproduce

1. Create `ActionFooter` component with `Text` component for the `end` prop. 
```jsx
<ActionFooter
    end={(
      <Text
        isWordWrapped
      >
        {'This is some very long text. This is some very long text. This is some very long text. This is some very long text.'}
      </Text>
    )}
/>
```
2. Load footer in ie 10.
3. Shrink screen enough that text should wrap.
4. Observe text does not wrap and continues off screen, creating a horizontal scroll bar.

## Additional Context / Screenshots

From [this stack overflow post](https://stackoverflow.com/questions/16808815/ie10-flexbox-p-element-non-wrapping), issue appears to be how IE handles word wrapping for flex boxes. And the terra action footer does use flexbox. The issue isn't observed when only using `Text` component outside `ActionFooter`.

Screenshot of issue reproduced with terra dev site:
![ie-issue](https://user-images.githubusercontent.com/31047566/83669506-4d13a800-a597-11ea-9c6e-80dccf56f48e.png)

## Expected Behavior

Text should wrap properly, since `Text` component is being used with `isWordWrapped` prop set to true.

## Possible Solution

From above stack overflow post, solution is to add css rule `flex: 0 1 auto` to the element wrapping the text element, which would be the action footer "start-actions" and "end-actions" css classes [here](https://github.com/cerner/terra-core/blob/7058b54cf297f2534a3163c643477388fe66a1e6/packages/terra-action-footer/src/ActionFooter.module.scss#L19). When testing this I confirmed it fixes the issue. Screenshot:
![ie-issue-fixed](https://user-images.githubusercontent.com/31047566/83669996-12f6d600-a598-11ea-9ee0-03feede5c0a3.png)

## Environment

* Component Name and Version: Reproduced on latest version of terra master branch
  * terra-text: v4.30.0
  * terra-action-footer: v2.44.0
* Browser Name and Version: IE 10
* Node/npm Version: Node v12.16.3. NPM v6.14.4
* Webpack Version: v4.43.0
* Operating System and version (desktop or mobile): Windows 10 VM. Desktop.

**Comment by JacksonJN** [comment]
I will create a PR for this fix shortly if there aren't any objections.

**Comment by ryanthemanuel** [comment]
@neilpfeiffer is this a valid use case?  From what I understand, we are not supposed to be using the Text component inside of the action footer.  If that's the case, then I don't think this is something that needs fixing.

**Comment by neilpfeiffer** [comment]
@ryanthemanuel - As long as we still support IE10 - this is a valid bug to fix. Not from whether or not the Terra-text component inside of an action-footer (we can't specify what content must or must not be used in action-footer), but because this is an inconsistency exclusively for IE10.

@JacksonJN you referenced this stack overflow [post](https://stackoverflow.com/questions/16808815/ie10-flexbox-p-element-non-wrapping), but it really doesn't describe reason why, compared to [this post](https://stackoverflow.com/questions/43979702/display-flex-not-working-on-internet-explorer/43979973) which describes why this is a problem, mainly for IE10, and the 17 Flexbugs and their workarounds.

This issue is listed as [Flexbug #6](https://github.com/philipwalton/flexbugs#flexbug-6):  _"The default `flex` value has changed"_.  
IE10 implemented the draft version of the spec in 2012, 
which at the time listed that ([outdated W3C](https://www.w3.org/TR/2012/WD-css3-flexbox-20120322/#flexibility)):
```
Initial Value: none
```
and
```
The keyword ‘none’ is equivalent to "0 0 auto".
```

\
\
But it has since been agreed upon as ([current W3C](https://www.w3.org/TR/css-flexbox-1/#flex-property)) :
```
Initial Value: 0 1 auto
```

\
\
\
I was also able to replicate the effect of the IE10 inconsistency with any content given to the standard action-footer that should force wrapping, including buttons, for situations of super-long labels and unhandled responsive styling/changes (the Centered and Block action-footer components are unaffected).

Normal layout:
<img width="830" alt="Screen Shot 2020-06-08 at 4 25 24 PM" src="https://user-images.githubusercontent.com/1355485/84083119-a5d3ae00-a9a6-11ea-8e0a-cc2c0161e4b1.png">

Wrapping from unhandled responsive changes:
<img width="343" alt="Screen Shot 2020-06-08 at 4 27 13 PM" src="https://user-images.githubusercontent.com/1355485/84083132-abc98f00-a9a6-11ea-88bf-35106fe88fc9.png">

With flex set to `flex: 0 0 auto` on `.start-actions` &`.end-actions` to mimic IE10:
<img width="344" alt="Screen Shot 2020-06-08 at 4 26 58 PM" src="https://user-images.githubusercontent.com/1355485/84083156-b97f1480-a9a6-11ea-98d6-1561e736342a.png">

\
\
\
Recommendation to fix with @JacksonJN suggestion for updating:
https://github.com/cerner/terra-core/blob/7058b54cf297f2534a3163c643477388fe66a1e6/packages/terra-action-footer/src/ActionFooter.module.scss#L17-L20
to:
``` 
  .start-actions,
  .end-actions {
    align-self: center;
    flex: 0 1 auto;
  }
```

Which will not affect any other browser or consumer, because it will simply be re-stating the default initial value, but will impact IE10 to then act like the other modern browsers as we would intend. 


### Note: 
**_This may be an issue with other uses of flexbox in Terra, so we should keep an eye out for other places we might need to also add this as corrective polyfill/shim for IE10._**
