### ISSUE TITLE
terra-form-checkbox add a prop to make the legend inline

### ISSUE THREAD

**Issue by gabeparra01** [cerner/terra-core#3110]
# Feature Request

## Description
The legend/label for terra-form-checkbox is always separated from the checkboxes by a new line. Is Terra UX open to the idea of adding a prop that will make the legend inline just like the checkboxes? The idea is to save space because the user will have to do a lot of scrolling in this particular window that we are using terra-form-checkbox in. I attached a screenshot of what my team has in mind for an inline legend.

## Additional Context / Screenshots
![Same line for legend and checkboxes](https://user-images.githubusercontent.com/42552940/89299391-338cec00-d62c-11ea-8f96-07a1b75feab7.png)

## @ Mentions
@StephenEsser answered my initial question in the [Terra UX support channel](https://teams.microsoft.com/l/message/19:3ed4d4d6ffba48138550b9a91a2b50b4@thread.skype/1596058018286?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1596058018286&teamName=Terra&channelName=UX%20Support&createdTime=1596058018286)

**Comment by neilpfeiffer** [comment]
Thanks @gabeparra01 for your request. 

UX already has backlogged designs & plans for creating left aligned labels/legends, but it will need to come as two different segments of work:

**1) Left-Aligned Labels in FORMS:**
----
When using left-aligned labels in forms with more than one question/answer, UX has requested that all the labels and all inputs have available a binding grid or column system, such that all the inputs maintain a vertical column relative to the longest label. In order to achieve this, an overarching form-layout component needs to be created such that you can give it multiple label and input types (text-input, textarea, select, radio/checkbox, etc.) that will keep the layout of the full unit working as one. Wrapping would be built-in and responsibility of the component. 

<img width="975" alt="Screen Shot 2020-08-06 at 7 11 32 AM" src="https://user-images.githubusercontent.com/1355485/89530995-19cae080-d7b5-11ea-8a50-fdcd7ab40675.png">

<img width="1037" alt="Screen Shot 2020-08-06 at 7 19 39 AM" src="https://user-images.githubusercontent.com/1355485/89531091-454dcb00-d7b5-11ea-86bf-ebfe17e75789.png">


**2) Left-Aligned Labels in TOOLBARS:**
----
When using left-aligned labels in Toolbars, the field component should be a different API, since things like filters and on/off settings cannot be set to required, would never have helptext or error text below it, and should never be set in an invalid or in-error status. 

Since toolbars are primarily horizontally aligned, instead of vertical, the labels would not need a similar grid-system and are free to be inline, with the responsibility on consumers to maintain enough horizontal space to prevent wrapping. 

\
\
\
\
\
\
\
\
**_Additional Considerations:_**

One other thing to note is that specific for radio buttons and checkboxes, and any form components used in small-width views, UX generally does not recommend the inline/left-aligned labels/legends at all. It does not provide much flexibility for translations to be able to grow in length and not wrap in weird ways, especially on small views. 

A quick check of your example if set in German might appear as:

 
<img width="790" alt="Screen Shot 2020-08-06 at 8 45 17 AM" src="https://user-images.githubusercontent.com/1355485/89539449-5c92b580-d7c1-11ea-938c-c8ae065ac637.png">

Or if the labels need the additional context and use the current wording, it's even longer:

<img width="787" alt="Screen Shot 2020-08-06 at 8 45 35 AM" src="https://user-images.githubusercontent.com/1355485/89539458-60263c80-d7c1-11ea-82f6-19078243bdd9.png">

Which shows that in the length required almost doubles, and would be forced to wrap in your narrow-width popover. 

I'd recommend to continue with the suggestion @StephenEsser  provided in your thread, with the label in the current position and setting your checkboxes to be inline, only if space allows for all translated strings for any language you need to account for, still fits on a single line without wrapping.

\
\
\
\
\
**_Issue Notes:_**
Removing the blocked labels, and closing this request. The above two items will be logged as new issues when they are prioritized to work and complete in the future.

Related previously logged issue: https://github.com/cerner/terra-core/issues/1608

**Comment by gabeparra01** [comment]
@neilpfeiffer I appreciate the example you provided with German translations. That is something that I did not consider. I will forward your explanation to my team
