### ISSUE TITLE
Animation to fade in and fade out for terra components.

### ISSUE THREAD

**Issue by tarunkolla** [cerner/terra-core#3114]
# Feature Request

## Description

I'm currently working on displaying terra-alerts for a user and was wondering if there is a possible way to add animation to fade in and fade out for the alerts. 

<kbd>
<img src=https://user-images.githubusercontent.com/35357999/89456232-2b66a680-d729-11ea-9fe9-0a2de78848ae.gif alt="terra alert gif"/>
</kbd>

## Additional Context / Screenshots

<kbd>
<img src=https://user-images.githubusercontent.com/35357999/89456405-71236f00-d729-11ea-8b9e-090037690236.png alt='terra alert screenshot'/>
</kbd>

## @ Mentions

@jeremyfuksa

**Comment by neilpfeiffer** [comment]
Terra currently does not employ transitions or animations except for some reserved cases like loading icons, primarily for two reasons:  
(1) because a large percentage of our software runs behind instances of Citrix and other similar virtualization software, with configuration settings that keeps visual resources limited and low, effectively killing a suitable animation-frame-rates and noticeable transitions 
(2) usually, when one ui element has an animation in/out, there are implied secondary byproducts of that animation. One example is delaying the execution of any action/onclick until after the animation has completed (otherwise the UI may repaint and you don't end up seeing the "out" animation). A second example is additional chained UI animations, using your banner as an example - before and after it animates in/out -- since the page content also will reflow (down when banners are added in, up when banners are removed), most likely a transition for the page content to fluidly fade/slide up/down would also need to be added (which _could_ potentially trigger then another chained animated effect). Keeping track of all these animation frame and execution of the event loop becomes challenging, something that we'd like to grow into as Terra matures.

**Comment by neilpfeiffer** [comment]
Closing as a enhancement to be explored again in the future, but not at the current time.
