### ISSUE TITLE
terra-table: overflow-y set to scroll on fill

### ISSUE THREAD

**Issue by skalyanmoguloju** [cerner/terra-core#3329]
# Bug Report

## Description
When consuming the terra-table with the fill prop. The scroll markers are being displayed on both the header and the body even when the content does not require the scroll. While investigating, I have identified the overflow-y value is set to scroll instead of auto.

Do we have any reasons for displaying the markers when there is no content to scroll?

Following is the reference links to the code:
https://github.com/cerner/terra-core/blob/main/packages/terra-table/src/Table.module.scss#L51
https://github.com/cerner/terra-core/blob/main/packages/terra-table/src/Table.module.scss#L66

## Additional Context / Screenshots
![image](https://user-images.githubusercontent.com/14007521/105395955-f2da5c80-5be4-11eb-8ea9-513816fed2f1.png)

## Expected Behavior
We should not see the scroll markers on the header and the body unless the content requires the scroll.

## Possible Solution
Update the overflow-y value to auto from scroll

**Comment by dkasper-was-taken** [comment]
Hi @skalyanmoguloju, the overflow-y set to scroll is intentional. The setting handles the presence of either fixed scroll bars (user setting) or a plugged-in mouse. The table is constructed from divs and as a result requires this work around for column alignment between the header and table body. The unfortunate side effect is in IE specifically, the scroll bar always displays in that fashion.
 
 I will be closing this issue.
