### ISSUE TITLE
terra-form-input for file input not working

### ISSUE THREAD

**Issue by spurohit126** [cerner/terra-core#3378]
# Bug Report

## Description
terra-form-input is used for file upload and the input file button does not show up as expected in IE.

## Steps to Reproduce
Load the document site in IE-11
Here is the link: https://engineering.cerner.com/terra-ui/components/terra-form-input/form-input/input
The file input shows up as in screenshot:
![image](https://user-images.githubusercontent.com/79724868/109357210-d8cd1300-784f-11eb-8e69-4e0f31a956fd.png)

## Expected Behavior
![image](https://user-images.githubusercontent.com/79724868/109357313-05812a80-7850-11eb-9efe-b6985617c9af.png)

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by ShettyAkarsh** [comment]
@spurohit126 , do you have a reduced test case for this issue ?

**Comment by spurohit126** [comment]
> @spurohit126 , do you have a reduced test case for this issue ?

We are using terra-form-input for file upload in our project. When the application is loaded in powerchart IE, the issue occurs. Attached is the screenshot.

![image](https://user-images.githubusercontent.com/79724868/109511624-3ab89300-7a71-11eb-8dfb-093b98e9e640.png)

The expected behavior is to display "Choose file" button.
Let me know if more information needed.

**Comment by ryanthemanuel** [comment]
@spurohit126 there are definitely some visual problems in IE11 here. One thing to note, however is we have made the decision to rely on the native browser implementation of type = "file" so the overall look of the input *will* be different in IE11. This issue will track on cleaning up the CSS to make sure that there isn't anything being truncated.

**Comment by pranav300** [comment]
What I have found is that to remove the truncation from the input in IE, we can change the input height from `2.142857rem` to `2.45rem`. Or else we can also add it as an IE-specific CSS.

@neilpfeiffer

**Comment by neilpfeiffer** [comment]
After investigation, since the input file type has native unique UI that is specific to each browser, and the file type was not originally designed for or tested as an original intended use of the terra-form-input, Terra decided the resolution to this bug issue will be to not fix the specific browser unique layout issues for the input file type at this time, but rather instead to remove all Terra styling and behaviors applied for the `type='file'`, which will allow for the component to fallback to all browser default native styles and UI, as well as a list of other types that also provide additional browser UI or behaviors.

Links to key comments from the PR #3386

- Documented Proposal: https://github.com/cerner/terra-core/pull/3386#discussion_r590259305
- Documented final changes: https://github.com/cerner/terra-core/pull/3386#issuecomment-820194408 

\
Also repeating here the comment of final change details for easy reference:

> **Changes:**
\
Since specific input types have native UI provided by browsers by default, like `type="file"`, and only `type="text"`, `type="number"`, and `type="password"` were originally designed for and tested as the terra-form-input component with intentional styling and behavior handling, we've decided to create a separation for types that are 'supported' (has Terra specific styling and behaviors) and those that are 'unsupported'. 
\
Rather than completely blocking those types that are unsupported, the decision is to conditionally skip binding all terra classes: the base `'form-input'`, plus the conditional `'form-error'`, `'form-incomplete'`, and the `theme`, yet still pass through any consumer provided classNames, and let the Terra component fall back to the original html native-browser default UI for those input types.
\
After testing, the final list of 'supported' and 'unsupported' `types` are as follows:
\
• **Supported Types** = 'text', 'number', 'password', 'email', 'search', 'tel', 'url', 'hidden'.
\
• **Unsupported Types** =  'date', 'datetime-local', 'month', 'time', 'week', 'color', 'file', 'range', 'checkbox', 'radio', 'button', 'reset', 'submit'.
\
\------------------------------
\
Note: If future enhancements provide Terra styling and behavior handling for any of the unsupported types, they can be added back to the list of supported types.
