### ISSUE TITLE
MultiSelectField component cuts off placeholder text

### ISSUE THREAD

**Issue by jm078962** [cerner/terra-core#3417]
# Bug Report

## Description

When reviewing the WDIO tests with fr locales for a project, it was noticed that the placeholder text in the MultiSelectField component was being cut off if the provided placeholder text was too long. I've included screenshots under the additional context/screenshots. The full placeholder text should read "Sélectionner une ou des classes de produits".

## Steps to Reproduce

1. Discovered the issue when reviewing WDIO snapshots for a project. We had screenshots of when the MultiSelectField component was closed and opened. When closed, the placeholder text was truncated with an ellipse. When opened, the placeholder text extended out a few additional characters before the remaining text was cut off. 
2. The placeholder text being used was "Sélectionner une ou des classes de produits".

## Additional Context / Screenshots

MultiSelectField Text Cutoff Close
![MultiSelectField Text Cutoff close](https://user-images.githubusercontent.com/82111845/113908762-84954700-979c-11eb-946c-33f9ba029c68.png)
MultiSelectField Text Cutoff Open
![MultiSelectField Text Cutoff](https://user-images.githubusercontent.com/82111845/113904424-afc96780-9797-11eb-8202-fd40f01f0bcc.png)

## Expected Behavior

The expected behavior is that the provided placeholder text is displayed or displays an ellipsis at the point of which the text is too long to be completely viewed. 

## Environment

* Component Name and Version: Terra Form MultiSelect Field v. 6.16.0
* Browser Name and Version: Chrome, Firefox, Internet Explorer
* Node/npm Version: Node 8.16.0/npm 6.4.1
* Webpack Version: 4.46.0
* Operating System and version (desktop or mobile): macOS Catalina version 10.15.7

## @ Mentions

@StephenEsser

**Comment by neilpfeiffer** [comment]
Thanks @jm078962. 
\
We have completed PR #3449 to resolve the visually clipping of the placeholder of the inner input. After it is published on npm, the placeholder text in inner input will correctly extend to the full width of the frames in the combobox, search, tag, and multiselect components.
\
However, even after the fix, there are still cases that the full placeholder may be truncated or clipped if the width of the select frame is smaller than the placeholder text, or as a user selects options, it causes the space of the input+placeholder to move and be reduced, thereby not providing a user the full placeholder message or complete context as to all the original text with no way to disclose it.
\
Example with the changes implemented (and select is wide enough to show the full placeholder):
![2021-06-04_17-18-55](https://user-images.githubusercontent.com/1355485/120880055-7c376d80-c58d-11eb-8c72-46d63e9bdb4f.png)
\
Example with the dropdown open and type-able search input is in focus:
![2021-06-04_17-19-21](https://user-images.githubusercontent.com/1355485/120880067-95d8b500-c58d-11eb-9e40-15ba2909978b.png)
\
Example showing how the placeholder may be clipped when options start to be selected:
![2021-06-04_17-21-16](https://user-images.githubusercontent.com/1355485/120880098-d3d5d900-c58d-11eb-9261-284c6888f3c2.png)

Example showing how the placeholder may still be truncated if the width isn't large enough for a language:
![2021-06-04_23-43-53](https://user-images.githubusercontent.com/1355485/120880282-249a0180-c58f-11eb-94d3-5a311050da7f.png)


----


### Best Practice Recommendation:
The UX recommendation and future direction for Terra is to remove custom placeholders, for this reason, as well as the fact that placeholder text is not reliably available to A11Y users as critical context or information about how the user should answer the question. Instead, UX recommends that you switch instead to either more descriptive help text, more descriptive forms labels, or provide additional face-up informational text as needed. 

As such, Terra has been working on uplifting the form components to remove consumer provided custom placeholder text, and instead, have a standard provided word as the provided placeholder for all cases. This PR #3094 when complete will provide standard placeholder translations, for example, English will be `- Select -`, and French will be `Sélectionner`:
https://github.com/cerner/terra-core/blob/289d8b73c48ec84d23edcc3e00ee46e446efbfed/packages/terra-form-select/translations/en-US.json#L3
https://github.com/cerner/terra-core/blob/289d8b73c48ec84d23edcc3e00ee46e446efbfed/packages/terra-form-select/translations/fr-FR.json#L4

A sample recommendation might be to instead move the details currently in the placeholder instead into your help text to say something like `Choisissez-en un ou plusieurs éléments, limite de 5`:
![2021-06-04_20-19-39](https://user-images.githubusercontent.com/1355485/120880551-0a612300-c591-11eb-9ac8-447786145b4e.png)


----


### Alternate Recommendation:

If you cannot restructure your placeholder message for the immediate term, an alternate but less accessible recommendation would be to add a secondary disclosure method for your placeholder text by adding it also as a tooltip via the `title` attribute, so the full text at least displays to the user when they mouse hover over the multiselect control.

Example showing how the tooltip can be added as a way to ensure the full placeholder text is shown 
(multiselect not in focus):
![2021-06-04_18-10-50](https://user-images.githubusercontent.com/1355485/120880766-da664f80-c591-11eb-9050-3be806dc68e9.png)

Example with the multiselect in focus and dropdown is open, but no options have been selected:
![2021-06-04_18-15-18](https://user-images.githubusercontent.com/1355485/120880801-0c77b180-c592-11eb-8bb7-a67656533d31.png)

Here is sample code of how to achieve adding the title attribute which results in the tooltip:
```diff
   <MultiSelectField
      label="Classe de produit"
      placeholder="Sélectionner une ou des classes de produits"
      selectId="multiSelectField"
+     selectAttrs={{ title: 'Sélectionner une ou des classes de produits' }}
      help="Limite de 5 éléments"
    >
      <MultiSelectField.Option value="1" display="Item Class 1" />
      <MultiSelectField.Option value="2" display="Item Class 2" />
      <MultiSelectField.Option value="3" display="Item Class 3" />
      <MultiSelectField.Option value="4" display="Item Class 4" />
      <MultiSelectField.Option value="5" display="Item Class 5" />
      <MultiSelectField.Option value="6" display="Item Class 6" />
  </MultiSelectField>
```

When a user starts selecting items, it would be recommended that text of the tooltip should also be updated to reflect the same contents of what is showing in the top section of the multiselect, so it re-confirms what the user is seeing and doesn't confuse a user:
![2021-06-04_18-30-50](https://user-images.githubusercontent.com/1355485/120880848-6c6e5800-c592-11eb-8636-b44f9b3ded8e.png)

----

### Summary:
This change will resolve the visual bug found of the placeholder text being clipped and truncated prematurely within the frame of the multi-select and not allowed to stretch the full width. It will not, however, prevent the placeholder from ever being truncated or clipped, by methods of forcing line wrapping or any additional disclosure mechanism. 

Also discovered during this bug investigation was that Chrome and Safari truncate placeholder text within an input when the text is too long to display when the input is not in focus. When the input is in focus, the text is not truncated, but clipped, and appears to be full and available to see via scroll, but the user is not able to see the full text via scrolling (only if there is full typed text within the input, not placeholder text). Firefox and IE when tested do not seem to have this same behavior. Terra's decision was to keep the behavior of each native browser without attempting to override, as the problem is better solved by the _Best Practice Recommendation_ given above.
