### ISSUE TITLE
[terra-paginator] Paginator Button not getting focused when clicked by the mouse.

### ISSUE THREAD

**Issue by pranav300** [cerner/terra-core#3439]
# Bug Report

## Description

The paginator buttons when clicked using the mouse do not get any of the focus styles.

## Steps to Reproduce

1. Go to any example in terra-paginator: https://engineering.cerner.com/terra-core/components/terra-paginator/paginator/paginator
2. Try clicking on the paginator buttons with the mouse. It doesn't show any focus styles.

## Expected Behavior

Buttons should show focus styles when clicked using the mouse

## Possible Solution

Handle mouse events similar to how key events are being handled [here](https://github.com/cerner/terra-core/blob/main/packages/terra-paginator/src/_PaginatorButton.jsx#L50)

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by neilpfeiffer** [comment]
@pranav300 I am not clear on what you are indicating that needs to be updated, as Terra intentionally toggles the visual styling of the in-focus state based on whether you are interacting with the UI via keyboard or mouse: turning the visual styling "off" for mouse interaction, and "on" for keyboard interaction. 

This was an intentional change added on PR #2686, where the paginator previously would show the focus glow after clicking with mouse, which was undesired: [screenshot example](https://github.com/cerner/terra-core/pull/2686/files?short_path=150fefd#diff-aa0db580feafd0d1d901a026c4681b8bf1d2b04a7d657e4f5d8aea5a5c4ae707)

Is there something different that is not being handled correctly? The pattern to hide the focus glow when clicking by mouse, but show interacting with the keyboard is meant to be consistent across terra in buttons, lists, tables, menus, navigation, and generally anything interactive.
