### ISSUE TITLE
Add example with datepicker inside modal

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/terra-core#360]
# Issue Description
We need to know if a datepicker will work inside of a modal. For this issue, create an example so we know the actual behavior.

<img src="https://cloud.githubusercontent.com/assets/8146159/26126400/11534fce-3a4b-11e7-991b-c3b519dc1cac.gif">

<img src="https://cloud.githubusercontent.com/assets/8146159/26126485/5f67f5de-3a4b-11e7-9ce9-bed87e524e11.png">

On smaller screens, the datepicker popup renders inside of the modal component and works as expected.

<img src="https://cloud.githubusercontent.com/assets/8146159/26126588/ce19833a-3a4b-11e7-8f90-b334ea48232b.png">

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Datepicker component works inside of a modal.

## Current Behavior
Datepicker does not work inside of a modal.

## Steps to Reproduce

1. Add Datepicker in Modal
2. Open datepicker and try to interact with it

## Environment

* Component Version: Modal v0, Datepicker v0
* Browser Name and Version: 
* Operating System and version (desktop or mobile):

**Comment by Matt-Butler** [comment]
![datepicker_inside_modal](https://cloud.githubusercontent.com/assets/8146159/26126400/11534fce-3a4b-11e7-991b-c3b519dc1cac.gif)

I am unable to select a date from the calendar when the datepicker is inside the modal. 

![screen shot 2017-05-16 at 3 21 34 pm](https://cloud.githubusercontent.com/assets/8146159/26126485/5f67f5de-3a4b-11e7-9ce9-bed87e524e11.png)

The datepicker popup renders outside the modal in the dom. It is outside of the trap focus component.

**Comment by Matt-Butler** [comment]
On smaller screens, the datepicker popup renders inside of the modal component and works as expected.
![screen shot 2017-05-16 at 3 24 04 pm](https://cloud.githubusercontent.com/assets/8146159/26126588/ce19833a-3a4b-11e7-8f90-b334ea48232b.png)

**Comment by Matt-Butler** [comment]
I added this branch with the example.
https://github.com/cerner/terra-core/tree/datepicker-in-modal

After starting the dev server, navigate to
http://localhost:8080/#/tests/modal-tests/datepicker

**Comment by Matt-Butler** [comment]
https://github.com/cerner/terra-core/blob/master/packages/terra-date-picker/src/DatePicker.jsx#L137
We should try removing the withPortalProp and see if that could fix our issue

**Comment by Matt-Butler** [comment]
I tried the react-datepicker using the [withPortal prop](https://hacker0x01.github.io/react-datepicker/#example-19). That also did not work. The datepicker is inaccessible because it is larger than the modal container. 

![withportal](https://cloud.githubusercontent.com/assets/8146159/26649079/39508030-460a-11e7-9754-62cdc362d290.gif)
The first datepicker is without the withPortal prop. The second datepicker uses the withPortal prop.

**Comment by dkasper-was-taken** [comment]
The issue is the focus trap that the modal uses.  Since the popup and calendar are both tether outside of the modal, they cannot receive clicks or focus.  The answer comes from using the "pause" functionality of the focus trap.  By managing the focus trap state we can allow both to continue functioning and on their dismissal restore the focus trap state.

I have several works arounds that I've implemented for both popup and calendar.
https://github.com/cerner/terra-core/tree/terra-popup-focus-example

Currently this is manually managed in the example. But the ideal solution would be to extend the behavior of the app delegate, to decorate requestFocus and releaseFocus capability, and for calendar and popup to take optional AppDelegate params. Then the modal manager can apply these functions similar to it's current actions. Internally the popup and calendar check for the presence of those functions to determine if they are in a modal, and selectively request and release focus.

I believe this kind of behavior is quite clean, and requires a user just pass the app delegate, so it's disclosure and content has to have zero knowledge of it's own location.  As a result, I think this is a good case to move modal manager and app delegate into the core repo, so we establish this as the intended behavior and use.  Otherwise we'll need HOC around everything to enforce this, and still require changes to expose functions on the base implementation.

**Comment by bjankord** [comment]
Released in terra-app-delegate v1.2.0, terra-date-picker v1.3.0, terra-modal-manager v1.3.0, and  terra-modal v1.3.0
