### ISSUE TITLE
Enhance or add a higher level component around the Image component to allow for a default image if the image fails to load

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-core#429]
# Issue Description
Certain situations (especially patient photos) require that there is a back up image if the given image fails to load.  It would be ideal to have a mechanism to expose this first class to consumers.  This could either be a prop on the existing Image component or a higher level component if need be.

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

**Comment by ryanthemanuel** [comment]
Let's go ahead and design this as if it is going to be a prop on the existing Image component.  Matt Schile, who is working on implementing the Demographics component, needs this functionality for the image in the demographics component.  We have requested that he work on this functionality.

**Comment by mschile** [comment]
Discussed on June 7th during the Terra sync with @bjankord, @mjhenkes, and @ryanthemanuel and decided create a higher level component for the patient photo that will contain an avatar to be displayed while the actual patient photo is being loaded.  Once the patient photo is loaded it will replace the avatar image.  If the patient photo fails to load, the avatar will remain in place.

### Design

#### Component name:
terra-patient-photo
terra-patient-image
terra-profile-image

#### Props:
**image**: terra-image

#### State:
**isLoading**: boolean used to indicate if the patient image is still loading
**isLoaded**: boolean to indicate if the patient image was successfully loaded.  Will be false if the patient image failed to load.

#### Flow:
1. Copy the properties (other than src) set on image prop to the internal avatar image to maintain a consistent look for the avatar and patient images.  Not sure I like copying all of the properties since there could be other properties that we would not want to copy, such as the onLoad and onError properties I plan on adding to image.  Instead of copying the properties, I could just replicate the properties on this new component.  Thoughts?
2. Set state to isLoading: true and isLoaded: false.
3. During render return a div that contains both the avatar and patient images.  The patient image will be hidden until it is successful.
4. If the onLoad event fires, update the state to isLoading: false and isLoaded: true.  Render only the loaded patient image.
5. If the onError event fires, update the state to isLoading: false and isLoaded: false.  Render only the avatar image.

I'm going to log another issue for terra-image to add two new properties to determine when an image has loaded.

**Comment by ryanthemanuel** [comment]
I like 'terra-profile-image'.  The question is would we want this to land in the terra-clinical space or the terra-core space.  I vote terra-core, as this profile could allow for various "people" concepts.

**Comment by ryanthemanuel** [comment]
Maybe more of a question for UX, but would we want to allow for a customized avatar in the props?

**Comment by dkasper-was-taken** [comment]
As to point 1:
The two cases I see.
 If your internal object is a pure icon/image, in which case we need to make a copy of the props, and delete the known undesired props, but pass the remaining props onto the object in the case that they are adding customProps.
If you internal object is a subcomponent that lives with the wrapper component, I'd say probably the best action would be, set the props for variant, isFluid, alt, height, width should be first class supported on your internal object. Then when consumed we pass all props onto the subcomponent, in the render pull out the white listed values, and delete the known undesired props from the remaining custom props, and add the remaining custom props onto the objects, similar to our handling in the our packages.

**Comment by mschile** [comment]
Spoke with @neilpfeiffer, @ryanthemanuel, and @mmalaker regarding if any animation is required for transitioning between the avatar and patient image and decided that we would not be implementing any animation at this time.

**Comment by mschile** [comment]
> Copy the properties (other than src) set on image prop to the internal avatar image to maintain a consistent look for the avatar and patient images. Not sure I like copying all of the properties since there could be other properties that we would not want to copy, such as the onLoad and onError properties I plan on adding to image. Instead of copying the properties, I could just replicate the properties on this new component. Thoughts?

Spoke with @ryanthemanuel and @dkasper-was-taken and decided to accept a terra-image and copy all of the props and remove any of the undesired props.

**Comment by ryanthemanuel** [comment]
Resolved by #501
