### ISSUE TITLE
Enable Icons to be Customized

### ISSUE THREAD

**Issue by mhemesath** [cerner/terra-core#587]
# Issue Description
The terra-consumer platform will need different icons. We need to build in the capability to allow the terra core icons to be changed.

One suggestion I have is using the [Define Plugin](https://webpack.js.org/plugins/define-plugin/) to conditionally flip between a `<use>` element and the default SVG.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by mhemesath** [comment]
It actually looks like this could be trivial using the [normal module replacement plugin](https://webpack.js.org/plugins/normal-module-replacement-plugin/). This would allow consumers to replace terra icons with their own quite easily.

**Comment by Matt-Butler** [comment]
If we get the naming to match up exactly, we can probably also use aliases.
https://webpack.js.org/configuration/resolve/#resolve-alias

```
alias: {
  'terra-icon': path.resolve(__dirname, 'node_modules/terra-consumer-icon')
}
```

**Comment by Matt-Butler** [comment]
I got it working on this branch: https://github.com/cerner/terra-core/tree/custom-icon

Datepicker example
http://localhost:8080/#/site/datepicker

**Comment by mhemesath** [comment]
Thats awesome, thanks for looking into this.

**Comment by amf9t2** [comment]
Brief discussion on the different approaches and suggestion to import custom icons.
* SVG Use
   * Pros -Consumers can redefine what icons are referenced via USE element with custom sprites
   * Cons - Large SVG sprites increase DOM size / slow down rendering performance. Switching a USE 
     reference updates all instances, where UX likely wants to update specific instances
* Alias approach 
Icon name same
Consumer can either import icon from terra-icon or terra-consumer-icon
Pros
Consumers can redefine what icons are referenced via alias in webpack config
Cons
Switching a alias in webpack updates all instances, where UX likely wants to update specific instances
* Normal-module-replacement-plugin
Icon name same
Consumer can either import icon from terra-icon or terra-consumer-icon
Pros
Consumers can redefine what icons are referenced via plugin in webpack config
Cons
Switching a plugin in webpack updates all instances, where UX likely wants to update specific instances
* Pass in icon via custom props
Pros
Icons can be set per component instance
Cons
Need to wrap the component to set custom icon
* We could add aliases specific to icon usage
Instead of only having chevron-left / chevron-right, we could add an icon alias for list-chevron. With that we can switch out only the icon for certain components.
Pros
Consumers can redefine what icons are referenced via alias in webpack config
Can alias only component specific icons
Cons
Possible pushback from UX for adding alias to their system

**Comment by bjankord** [comment]
We are making icons themable via CSS background images.
