### ISSUE TITLE
Create consumer theme for form input

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#755]
# Issue Description
To match consumer UX, we want to enable the theming of terra input.
Here is a screenshot of the current component:
<img width="692" alt="screen shot 2017-08-28 at 9 27 53 am" src="https://user-images.githubusercontent.com/633148/29777908-3df3c214-8bd3-11e7-9580-cf9128e45c01.png">

Evaluate if we will solve this issue as well
https://github.com/cerner/terra-core/issues/755

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
CSS custom properties are added to enable the theming of the `<Input />` component to match consumer UX visuals.

**Comment by WhiteLight1107** [comment]
# Tech Design
4 Consumer Theme states need to be added to a themes.scss file for input 
-Default
-Focus
-Active
-Disabled 

In order to achieve this variables in input.scss will be needed to change into variables so they can be modified in consumer theme for example with height currently it is

```
//Input.scss
:local {
  ...
  height: 1.857em;
  ...
   &[type='checkbox'],
   &[type='radio'] {
      height: auto;
      ...
    }
 ...
}
```
This will need to change to 

```
//Input.scss
:local {
  ...
  height: var(--terra-input-height, 1.857em_;
  ...
   &[type='checkbox'],
   &[type='radio'] {
      height: auto;
      ...
    }
 ...
}

//_themes.scss
@include cerner-consumer-theme {
   --terra-input-height: 32px;
}

```

This way the input text box can be modified for the consumer theme while keeping the defaults for legacy terra-core input, this "pattern" will need to be followed for all of the css props that would change in the consumer theme opacity,border etc.

**Comment by alex-bezek** [comment]
With the currently recommended tech design, we would have to override every value we set back to the original values specifically for radio/check boxes. This could get messy and easy to forget or get things wrong. Additionally, when we start theming the control.scss file more, and creating our custom inputs, there would be css affecting radio/checkbox in multiple css files, and i'm not actually even sure how the specificity wins out here.

What if we instead used a not selector, or maybe radio/check shouldn't even consume the same base input as its going to look very different. @JakeLaCombe  thoughts?

**Comment by WhiteLight1107** [comment]
@alex-bezek  perhaps that would be the right move would be to move scss for checkbox and radio from Input.scss to the Control.scss file

**Comment by WhiteLight1107** [comment]
So for example it would work like this 

```
//Input.scss

:local {
...
.input:not([type='checkbox']):not([type='radio']) {
  //input box css variables would go here defaulted 
  //to what the current values are for example..  
  border: var(--terra-input-border, #dedfe0 solid 1px;);
  ...
}
}
```
Then all radio and checkbox css would move to the input class in Control.scss so 
.input in Control.scss would become
```
   .input {
      vertical-align: middle;
      border: 0;
      font-size: 1em;
      display: inline-block;
      height: auto;
      width: auto;
      padding: 0.178em;
    }
```

**Comment by StephenEsser** [comment]
Using the not selector is a good indication of poor encapsulation. My vote is for the second approach Alex suggested. The Control should either not consume the base input or the base input should contain the bare minimum styles that apply to every input and do not cause conflicts. It feels awkward the base Input.scss immediately overrides declared styles to satisfy radio / checkbox and then then Control.scss also adds its' own styles.

There's already some conflicting styles in Input.scss from Control.scss
https://github.com/cerner/terra-core/blob/master/packages/terra-form/src/Control.scss#L5
https://github.com/cerner/terra-core/blob/master/packages/terra-form/src/Input.scss#L15

My opinion is that radio / checkbox specific theme-able styles should be encapsulated in Control.scss, or Radio.scss / Checkbox.scss respectively

**Comment by bjankord** [comment]
> perhaps that would be the right move would be to move scss for checkbox and radio from Input.scss to the Control.scss file and then use CSS variables in Input.scss for what needs to be themed for input box

+1 to this idea.

**Comment by WhiteLight1107** [comment]
Ok, so I'll encapsulate the radio/checkmark in their own scss files, probably better for them to have their own separate ones for in the future when theming starts happening for checkmark and radio.

**Comment by WhiteLight1107** [comment]
# Tech Design
4 Consumer Theme states need to be added to a themes.scss file for input 
-Default
-Focus
-Active
-Disabled 

In order to achieve this variables in input.scss will need to be added, for example in order to handle height 
```
//Input.scss
  height: var(--terra-input-height, 1.857em);

//_themes.scss
  --terra-input-height: 32px;
``` 

With the current design checkbox and radio would have its css overwritten so the css for checkbox and radio that is currently in input.scss will be moved into control.scss, perhaps in the future this will be broken up into radio.scss/checkmark.scss for theming purposes.

Therefor the based input component will need to make sure that it does not apply the .input class from Input.scss to inputs with type radio or checkmark.

A _themes.scss file will be need to be created this will contain all the themes for the terra-form package.

**Comment by bjankord** [comment]
> Therefor the based input component will need to make sure that it does not apply the .input class from Input.scss to inputs with type radio or checkmark.

This logic can either be added in the Input.jsx file as a conditional check on type or we could make Control render its own input element instead of wrapping the `<Input />` component. I'm fine with either way.

**Comment by WhiteLight1107** [comment]
@bjankord  was thinking of modifying this line: https://github.com/cerner/terra-core/blob/master/packages/terra-form/src/Input.jsx#L58 
to something like this instead of having control render its own input element 
```
    const inputClasses = 
    cx([(customProps.type === 'radio' || customProps.type === 'checkbox') ? 
    '' : 'input', additionalInputProps.className]);
```

**Comment by neilpfeiffer** [comment]
OCS input has been created and will be resolved by current work tracked instead with this new issue #1207
