### ISSUE TITLE
Popup closes when keyboard opens on android

### ISSUE THREAD

**Issue by hboege** [cerner/terra-core#797]
# Issue Description
When the keyboard displays on a tablet, it causes the view to resize, thus closing any open popups.  If the popup contains a text field, there is no way for a tablet user to enter text.

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
A popup that has a text box should not close when the keyboard opens.

## Current Behavior
The popup closes when the view resizes.

## Steps to Reproduce
We will post a video with a specific example, but here is the general idea.
1. On a tablet, display a modal.  Display a popup, with a text box, from the header in the modal.
2. Click in the text box, so it has focus and the keyboard displays. 
3. Notice the popup disappears.

## Environment
* Component Version: terra-popup 1.8.0
* Browser Name and Version: Chrome
* Operating System and version (desktop or mobile): mobile Samsung tablet

**Comment by dkasper-was-taken** [comment]
We will need to discuss possible solutions, as exposing the ability to disable resize dismissal may cause vulnerabilities, so we need to evaluate concerns.

**Comment by hboege** [comment]
David had done some more testing, and found that the keyboard caused the popup to close on an Android device, but not iOS device.

**Comment by neilpfeiffer** [comment]
Adding to this issue a similar bug discovered by Message Center. A summary of the issue they've reported:

### Issue Description/Current Behavior
Message Center has a custom toolbar with a compose message box (similar to a text messaging input) and a "send" button and "more" (plus/"+") button. When the keyboard is showing, pressing the "more" (plus/"+") button closes both the keyboard and the popup (not the intended use).

### Expected Behavior
Keyboard stays displayed and the popup displays over the page content (or if we need a new control that provide an action sheet or new row of actions) so user can add a photo or a quick message. _(See attached screenshot for expected behavior.)_

### Steps to Reproduce
1. The compose message text box is in focus and keyboard is displayed…
2. The user selects the "more" (plus/"+") button to display the quick message/picture message popup
3. The popup flashes and disappears, and the keyboard is removed. _(Once the keyboard is removed and the “more” button is selected it works just fine, but that’s obviously not intuitive to a user.)_

![image](https://user-images.githubusercontent.com/1355485/30817412-6a953552-a1de-11e7-9d37-d203d7230571.png)

**Comment by laurunning** [comment]
Hello, I wanted to add a bit to the issue Neil describes above. This is happening in CareAware Messenger in **both** iOS and Android.

**Comment by bjankord** [comment]
@hboege @neilpfeiffer @laurunning Thanks for the detailed issue report, this helps us a lot. As @dkasper-was-taken mentioned, a fix for this will need will discussion around possible solutions. I would add that the change to fix this is likely not a trivial change but we'll work on setting up a meeting and start exploring how we could get this to work following the noted expected behavior.
