### ISSUE TITLE
On Windows 10, line ending diffs show up in commit and error out in ESLint.

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#816]
# Issue Description
On Windows 10, line ending diffs show up in commit and error out in ESLint. 

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Contributors can run eslint on Windows and commit without modifications to line endings.

## Current Behavior
Contributors can not run eslint on Windows and cannot commit without modifications to line endings.

## Steps to Reproduce
1. Clone repo
2. Run `npm install`
4. Run `npm test` or `npm run lint:js`

## Environment
* Operating System and version (desktop or mobile): Windows 10

**Comment by emilyrohrbough** [comment]
> The linebreaks (new lines) used in windows operating system are usually carriage returns (CR) followed by a line feed (LF) making it a carriage return line feed (CRLF) whereas Linux and Unix use a simple line feed (LF). The corresponding control sequences are "\n" (for LF) and "\r\n" for (CRLF).

ESlint [linebreak documention](https://eslint.org/docs/rules/linebreak-style) says versioning tools like git will convert files to CRLF for windows machines, however will convert back to LF when committing a change. To fix this we should add 
`*.js text eol=lf` and `*.jsx text eol=lf` to .gitattributes.

One option to addressing this issue is to add the `--fix` flag before running the linter. A potential downside to this flag is it will attempt to automatically as much linter as possible, not just line-end. (I was able to change a test file to CRLF and --fix addressed the line end issues.)

Regardless, windows developers should configure the line-ending settings for the text editor being used to prevent CRLF line ends:

**For Atom:**
1. Go to Preferences
2. Select Packages 
3. Under Core Packages, select Settings for line-ending-selector
4. Choose 'LF' for default line ending.

**Comment by bjankord** [comment]
> To fix this we should add
*.js text eol=lf and *.jsx text eol=lf to .gitattributes.

+1, lets go with this and see if it resolves the eslint errors.

**Comment by Singleton06** [comment]
I think this can be resolved now
