### ISSUE TITLE
Add *.idea* to .gitignore

### ISSUE THREAD

**Issue by dv297** [cerner/terra-core#839]
# Issue Description
JetBrains IDE's (RubyMine, WebStorm) create a hidden directory ".idea" whenever you open a directory as a project. These files are workspace specific and should be ignored.

Because this is a monorepo, opening the whole entire repo in the IDE usually just crashes the IDE on slower machines. So I've been opening just the particular package I'm working on in WebStorm, which means the .idea directory is in a subdirectory of the project. The expression "*.idea*" should solve this.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [X] Other

## Expected Behavior
* After opening the project in any JetBrains IDE, running "git status" should not show any .idea directory.
* After opening a subdirectory of the project in any JetBrains IDE, running "git status" should not show any .idea directory.

## Current Behavior

After opening the project in any JetBrains IDE, running "git status" currently shows the .idea directory.

## Steps to Reproduce
1. Open project in any JetBrains IDE
2. Run `git status`

**Comment by StephenEsser** [comment]
I don't think it is inherently bad to blacklist the .idea file but this seems to be an artifact of the IDE and is a problem for every project that opens in that IDE. 

I'd recommend adding .idea to your local .gitignore_global file on your machine rather than every project individually.

RubyMine attempts to index the node_modules directory and simply isn't built to handle the size of the mono repos web assets.

The IDE switch can be difficult, but I'd recommend migrating over to Atom or Sublime if you can get a license. Atom is free, open source, and doesn't crash loading the project like RubyMine does.

**Comment by dv297** [comment]
That's fine. Honestly, this is the first time I've heard of a global
gitignore, so thanks for that! I wouldn't be surprised if others didn't
know about a global one either, so the minimal cost of adding an entry to
the project's gitignore vs the overhead a dev has to know to not be annoyed
seems justified to me. But I understand that opting to not add an entry for
every IDE and editor can just be a project preference thing. I've just seen
projects opt otherwise.

I'm good with either addressing it or closing this with the global
gitignore as the preferred route.

**Comment by StephenEsser** [comment]
I think there is some value in adding the change. The global ignore is pretty nifty though
