### ISSUE TITLE
Search Field: autosearch & minLength change

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#952]
# Related Issues:
[#943 - Search Field: clear field](https://github.com/cerner/terra-core/issues/943)
[#953 - Search Field: disabled state & fits container](https://github.com/cerner/terra-core/issues/953)

----

# Issue Description
New features to add to the search field component:
1. Add keyboard interaction - listen for `enter` key to execute search when input has tab focus.
2. add a new prop to disable autosearch, so that search is only on click/enter synchronous execution.

## Issue Type

- [ ] New Feature
- [X] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
- items listed above

## Current Behavior
- default search is executed at 250ms and only after 2 minimum characters

**Comment by neilpfeiffer** [comment]
cc: @Singleton06 @bjankord @mjhenkes

**Comment by Singleton06** [comment]
There are a couple of ambiguities that I would like cleared up before creating a tech design.
* Will the enter key to search always be enabled or are we thinking that it will be configurable so that consumers can choose not to have it if they want?  Will this be on by default or no?
* Could you clarify a bit more what you mean by indicating that we need to make an adjustment to the `searchDelay` and `minimumSearchTextLength` such that there is no default? Are you indicating that this is only in the situation where enter is able to be used?  Are we talking about literally just changing the default values? Our particular use case was just to be able to disable these.  This could be by simply providing a flag that turns of auto-searching.

**Comment by mjhenkes** [comment]
- Enter to search should always be available. 
- Removing the default value for` searchDelay` and `minimumSearchTextLength` would be a non passive change and should be avoided. To disable it there will have to be an additional prop passed in.

**Comment by Singleton06** [comment]
# Tech design for the search field disabling auto search and enter to search
## Summary:
Upgrade the search field control to be able to press enter to force a search at any time (without waiting). Additionally, for some consumers, it is desired to disable the auto-search functionality.

## Requirements Added
* Allow the enter key to trigger search, either valid (calling the onSearch prop) or invalid (calling the onInvalidSearch function).
  * The search is considered valid if it meets the minimumSearchTextLength and onSearch has been specified
  * The search is considered invalid if it does not meet the minimumSearchTextLength and onInvalidSearch has been specified.


## Responsiveness
No change should occur to the responsiveness.

## Bidirectionality
No change should occur to the bidirectionality.

## Accessibility
This might help improve accessibility because the enter button can be used to search.

## React Props
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| autoSearch | bool | true | Determines whether or not search should be triggered automatically. If `false`, the user will have to manually trigger the search, essentially overriding `searchDelay`. |


## Example
```
<SearchField
  autoSearch={false}
/>
```

**Comment by mjhenkes** [comment]
+1

**Comment by bjankord** [comment]
+1

**Comment by emilyrohrbough** [comment]
+1

**Comment by StephenEsser** [comment]
+1

**Comment by skalyanmoguloju** [comment]
Can I get this assigned to me.

**Comment by mjhenkes** [comment]
@skalyanmoguloju @kschuste is going to be doing this work within the next couple of weeks.

**Comment by Singleton06** [comment]
@skalyanmoguloju, how quickly are you going to be working on this?  I have changes that I was going to combine with this work given our short deadline for needing these enhancements.  Since we have about 6 enhancements that we need to get done on the search field, I didn't want to go through multiple rounds of validation and the changes that are needing to be done are very close to each other and would likely result in merge conflicts if multiple people were to do this work.

Would you be opposed with this being assigned to me and I can combine it as part of the work that I already have done [here](https://github.com/Singleton06/terra-core/commit/d1801feda364264569c1354d38b05c3104a82a48)?

**Comment by mjhenkes** [comment]
@Singleton06 pr #1004 has been submitted to address this issue.

**Comment by tm4027** [comment]
JIRA created

**Comment by jmsv6d** [comment]
Closed with #1004
