### ISSUE TITLE
popup position not adjusted with dynamic height

### ISSUE THREAD

**Issue by zhongyn** [cerner/terra-core#967]
# Issue Description
When popup prop contentHeight is "auto", the popup position is not adjusted as the content height changes. In the gif example below, the bottom part of popup is pushed outside the window:

![popup-position](https://user-images.githubusercontent.com/5943136/32020925-67486a74-b997-11e7-9a0d-dc050a7dfff4.gif)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
When content height changes, popup position should adjust itself. In the gif exmaple above, it should push up the top part instead of pushing down the bottom.

## Environment

* Component Version: 1.12.0
* Browser Name and Version: Chrome
* Operating System and version (desktop or mobile): Mac OS

**Comment by dkasper-was-taken** [comment]
Live updates to content are not supported in this implementation. If the size of the popup needs change, the component managing the popup would need to trigger another render. This will pick up the new size of the content. This is a result of the popup lays out when it's triggered initially captures it's size, then does a second render to determine if the size fits within it's bounding element. Whether that being the window or a boundingRef. Following that it's positioned. I'd looked at using a resize observer, but that became difficult to differentiate between resize events from the content and resize events from being bound. This is easier handled by the implementing component, since the same loop would occur, and intentional resizes based on user actions are easier determined.

**Comment by dkasper-was-taken** [comment]
I have created a working example using animations, but I'm not sure that the performance implications are worth it, requiring 2 renders per animation frame. Animations combined with positioning also creates significant blur artifacts.

Animations aside, there is a significant jumping behavior when transitioning sizes that affect attachment points.

I think we'd need to evaluate whether or not this behavior is a valid design pattern. I know from other designs, we've been keeping popup sizes static during actions while open.

**Comment by dkasper-was-taken** [comment]
I should clarify, these performance issue are not limited to cpu bound mobile, but clearly visible even on chrome/firefox on desktop.

**Comment by dkasper-was-taken** [comment]
As a result of these scenario, I think the best way to achieve the desired functionality would be to code a custom component using absolutely positioned with a bottom attachment to achieve the desired effect.

**Comment by bjankord** [comment]
We've reviewed this use case and believe it goes beyond the use case of popups. @neilpfeiffer has recommended that this is a new unique component that needs work to match the use case displayed in the attached image.
